env: staging
replicas: 1
canary:
  config: |-
    upstream weighted {
        #server zendesk:8088 weight=9;
        server 127.0.0.1:8888 weight=1;
    }
    server {
        listen 127.0.0.1:8888;

        location / {
            rewrite "(?i)/(.*)" /faq/$1 break;
            rewrite "(?i)/$" /faq/ break;
            proxy_pass http://orochi.consumer;
        }
    }
    server {
        listen 80;

        # this is for health check from route53, should not be routed.
        location = /api/status {
            proxy_pass http://zendesk:8088;
        }

        # this is for orochi move permanently rule which should route to orochi, not zendesk.
        location /faq/api/ {
            proxy_pass http://orochi.consumer;
        }

        # weight route to zendesk or orochi.
        location /api/ {
            proxy_pass http://weighted;
        }

        # the rests to zendesk.
        location / {
            proxy_pass http://zendesk:8088;
        }
    }
