// +build integration

package integration

import (
	"encoding/json"
	"net/http"
	"net/url"
	"testing"
	"time"

	"github.com/go-test/deep"

	"github.com/honestbee/Zen/errs"
)

func TestHandlersArticles(t *testing.T) {
	ts := newTserver()
	defer ts.closeAll()
	testCases := []struct {
		description  string
		args         url.Values
		addr         string
		expect       map[string]interface{}
		expectStatus int
	}{
		{
			description: "testing normal en-us locale case",
			addr:        "/api/sections/115004118448/articles",
			args: url.Values{
				"locale":       {"en-us"},
				"country_code": {"tw"},
			},
			expectStatus: http.StatusOK,
			expect: map[string]interface{}{
				"articles": []interface{}{
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115015959188,
						"author_id":        24400224208,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         0,
						"vote_sum":         0,
						"vote_count":       0,
						"created_at":       time.Date(2017, 12, 27, 3, 14, 16, 0, time.UTC),
						"updated_at":       time.Date(2017, 12, 27, 3, 14, 48, 0, time.UTC),
						"source_locale":    "zh-tw",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2017, 12, 27, 3, 14, 16, 0, time.UTC),
						"label_names":      []string{},
						"country_code":     "tw",
						"url":              "https://honestbeehelp-tw.zendesk.com/api/v2/help_center/en-us/articles/115015959188-What-can-I-do-when-my-cart-is-locked-.json",
						"html_url":         "https://help.honestbee.tw/hc/en-us/articles/115015959188-What-can-I-do-when-my-cart-is-locked-",
						"name":             "What can I do when my cart is locked?",
						"title":            "What can I do when my cart is locked?",
						"body":             "<p>When there is an error completing your checkout,your cart will be temporarily locked to prevent further changes to your order. To unlock your cart,click ‘Yes,unlock my cart,’ when prompted.</p>",
						"locale":           "en-us",
					},
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115015885547,
						"author_id":        24400224208,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         0,
						"vote_sum":         0,
						"vote_count":       0,
						"created_at":       time.Date(2017, 12, 27, 3, 12, 58, 0, time.UTC),
						"updated_at":       time.Date(2017, 12, 27, 3, 13, 42, 0, time.UTC),
						"source_locale":    "zh-tw",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2017, 12, 27, 3, 12, 58, 0, time.UTC),
						"label_names":      []string{},
						"country_code":     "tw",
						"url":              "https://honestbeehelp-tw.zendesk.com/api/v2/help_center/en-us/articles/115015885547-What-is-honestbee-s-information-security-policy-.json",
						"html_url":         "https://help.honestbee.tw/hc/en-us/articles/115015885547-What-is-honestbee-s-information-security-policy-",
						"name":             "What is honestbee’s information security policy?",
						"title":            "What is honestbee’s information security policy?",
						"body":             `<p>honestbee takes your privacy seriously and complies with all the relevant laws to ensure your details are kept secure. Read our <a href="https://www.honestbee.tw/privacy-policy">Privacy Policy</a> for more information.</p>`,
						"locale":           "en-us",
					},
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115015885507,
						"author_id":        24400224208,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         0,
						"vote_sum":         0,
						"vote_count":       0,
						"created_at":       time.Date(2017, 12, 27, 3, 11, 30, 0, time.UTC),
						"updated_at":       time.Date(2018, 1, 10, 6, 7, 41, 0, time.UTC),
						"source_locale":    "zh-tw",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2018, 1, 10, 6, 7, 41, 0, time.UTC),
						"label_names":      []string{},
						"country_code":     "tw",
						"url":              "https://honestbeehelp-tw.zendesk.com/api/v2/help_center/en-us/articles/115015885507-How-can-I-change-my-email-address-.json",
						"html_url":         "https://help.honestbee.tw/hc/en-us/articles/115015885507-How-can-I-change-my-email-address-",
						"name":             "How can I change my email address?",
						"title":            "How can I change my email address?",
						"body":             `<p>Currently,it’s not possible to change your email address. To register with a different email address,please create a new account.</p>`,
						"locale":           "en-us",
					},
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115015959168,
						"author_id":        24400224208,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         0,
						"vote_sum":         -2,
						"vote_count":       -2,
						"created_at":       time.Date(2017, 12, 27, 3, 8, 5, 0, time.UTC),
						"updated_at":       time.Date(2018, 3, 6, 12, 39, 30, 0, time.UTC),
						"source_locale":    "zh-tw",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2018, 1, 10, 6, 7, 41, 0, time.UTC),
						"label_names":      []string{},
						"country_code":     "tw",
						"url":              "https://honestbeehelp-tw.zendesk.com/api/v2/help_center/en-us/articles/115015959168-How-can-I-change-my-credit-card-password-or-delivery-address-.json",
						"html_url":         "https://help.honestbee.tw/hc/en-us/articles/115015959168-How-can-I-change-my-credit-card-password-or-delivery-address-",
						"name":             "How can I change my credit card,password or delivery address?",
						"title":            "How can I change my credit card,password or delivery address?",
						"body":             `<p>Log in to your account and go to your profile icon at the top right corner. Select Settings from the dropdown menu to edit your details.</p>`,
						"locale":           "en-us",
					},
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115015959148,
						"author_id":        24400224208,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         0,
						"vote_sum":         -1,
						"vote_count":       1,
						"created_at":       time.Date(2017, 12, 27, 2, 59, 48, 0, time.UTC),
						"updated_at":       time.Date(2018, 3, 2, 5, 59, 58, 0, time.UTC),
						"source_locale":    "zh-tw",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2017, 12, 27, 3, 6, 54, 0, time.UTC),
						"label_names":      []string{},
						"country_code":     "tw",
						"url":              "https://honestbeehelp-tw.zendesk.com/api/v2/help_center/en-us/articles/115015959148-Help-I-ve-forgotten-my-password-.json",
						"html_url":         "https://help.honestbee.tw/hc/en-us/articles/115015959148-Help-I-ve-forgotten-my-password-",
						"name":             "Help! I’ve forgotten my password.",
						"title":            "Help! I’ve forgotten my password.",
						"body":             "<p>Click on the Forgot Password link on the Login page and enter your registered email address. We’ll send you an email to reset your password. Occasionally emails end up in the junk/spam folder. Take a look there.</p>",
						"locale":           "en-us",
					},
				},
				"page":       1,
				"per_page":   30,
				"page_count": 1,
				"count":      5,
			},
		},
		{
			description: "testing normal zh-tw locale case",
			addr:        "/api/sections/115004118448/articles",
			args: url.Values{
				"locale":       {"zh-tw"},
				"country_code": {"tw"},
			},
			expectStatus: http.StatusOK,
			expect: map[string]interface{}{
				"articles": []interface{}{
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115015959188,
						"author_id":        24400224208,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         0,
						"vote_sum":         0,
						"vote_count":       0,
						"created_at":       time.Date(2017, 12, 27, 3, 14, 16, 0, time.UTC),
						"updated_at":       time.Date(2017, 12, 27, 3, 14, 48, 0, time.UTC),
						"source_locale":    "zh-tw",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2017, 12, 27, 3, 14, 16, 0, time.UTC),
						"label_names":      []string{},
						"country_code":     "tw",
						"url":              "https://honestbeehelp-tw.zendesk.com/api/v2/help_center/zh-tw/articles/115015959188-%E6%88%91%E7%9A%84%E8%B3%BC%E7%89%A9%E8%BB%8A%E9%8E%96%E4%BD%8F%E4%BA%86-%E8%A9%B2%E6%80%8E%E9%BA%BC%E8%BE%A6-.json",
						"html_url":         "https://help.honestbee.tw/hc/zh-tw/articles/115015959188-%E6%88%91%E7%9A%84%E8%B3%BC%E7%89%A9%E8%BB%8A%E9%8E%96%E4%BD%8F%E4%BA%86-%E8%A9%B2%E6%80%8E%E9%BA%BC%E8%BE%A6-",
						"name":             "我的購物車鎖住了，該怎麼辦？",
						"title":            "我的購物車鎖住了，該怎麼辦？",
						"body":             "<p>當結帳出現錯誤時，您的購物車會暫時被鎖住，以避免您的訂單出現異動。要解鎖您的購物車，請在出現提示時，點選「是的，解鎖我的購物車」。</p>",
						"locale":           "zh-tw",
					},
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115015885547,
						"author_id":        24400224208,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         0,
						"vote_sum":         0,
						"vote_count":       0,
						"created_at":       time.Date(2017, 12, 27, 3, 12, 58, 0, time.UTC),
						"updated_at":       time.Date(2017, 12, 27, 3, 13, 42, 0, time.UTC),
						"source_locale":    "zh-tw",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2017, 12, 27, 3, 12, 58, 0, time.UTC),
						"label_names":      []string{},
						"country_code":     "tw",
						"url":              "https://honestbeehelp-tw.zendesk.com/api/v2/help_center/zh-tw/articles/115015885547-honestbee-%E7%9A%84%E5%AE%89%E5%85%A8%E6%94%BF%E7%AD%96%E7%82%BA%E4%BD%95-.json",
						"html_url":         "https://help.honestbee.tw/hc/zh-tw/articles/115015885547-honestbee-%E7%9A%84%E5%AE%89%E5%85%A8%E6%94%BF%E7%AD%96%E7%82%BA%E4%BD%95-",
						"name":             "honestbee 的安全政策為何？",
						"title":            "honestbee 的安全政策為何？",
						"body":             `<p>honestbee 很重視您的隱私，並遵循所有相關法規以確保您的資訊安全。請閱讀我們的<a href="https://www.honestbee.tw/privacy-policy">隱私權政策</a>以了解更多資訊。</p>`,
						"locale":           "zh-tw",
					},
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115015885507,
						"author_id":        24400224208,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         0,
						"vote_sum":         0,
						"vote_count":       0,
						"created_at":       time.Date(2017, 12, 27, 3, 11, 30, 0, time.UTC),
						"updated_at":       time.Date(2018, 1, 10, 6, 7, 41, 0, time.UTC),
						"source_locale":    "zh-tw",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2018, 1, 10, 6, 7, 41, 0, time.UTC),
						"label_names":      []string{},
						"country_code":     "tw",
						"url":              "https://honestbeehelp-tw.zendesk.com/api/v2/help_center/zh-tw/articles/115015885507-%E5%A6%82%E4%BD%95%E6%9B%B4%E6%94%B9%E9%9B%BB%E5%AD%90%E4%BF%A1%E7%AE%B1-.json",
						"html_url":         "https://help.honestbee.tw/hc/zh-tw/articles/115015885507-%E5%A6%82%E4%BD%95%E6%9B%B4%E6%94%B9%E9%9B%BB%E5%AD%90%E4%BF%A1%E7%AE%B1-",
						"name":             "如何更改電子信箱？",
						"title":            "如何更改電子信箱？",
						"body":             `<p>您的電子信箱目前無法更改。若要以不同信箱進行註冊，請建立新帳號。</p>`,
						"locale":           "zh-tw",
					},
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115015959168,
						"author_id":        24400224208,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         0,
						"vote_sum":         -2,
						"vote_count":       -2,
						"created_at":       time.Date(2017, 12, 27, 3, 8, 5, 0, time.UTC),
						"updated_at":       time.Date(2018, 3, 6, 12, 39, 30, 0, time.UTC),
						"source_locale":    "zh-tw",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2018, 1, 10, 6, 7, 41, 0, time.UTC),
						"label_names":      []string{},
						"country_code":     "tw",
						"url":              "https://honestbeehelp-tw.zendesk.com/api/v2/help_center/zh-tw/articles/115015959168-%E5%A6%82%E4%BD%95%E6%9B%B4%E6%94%B9%E4%BF%A1%E7%94%A8%E5%8D%A1-%E5%AF%86%E7%A2%BC%E6%88%96%E9%80%81%E8%B2%A8%E5%9C%B0%E5%9D%80-.json",
						"html_url":         "https://help.honestbee.tw/hc/zh-tw/articles/115015959168-%E5%A6%82%E4%BD%95%E6%9B%B4%E6%94%B9%E4%BF%A1%E7%94%A8%E5%8D%A1-%E5%AF%86%E7%A2%BC%E6%88%96%E9%80%81%E8%B2%A8%E5%9C%B0%E5%9D%80-",
						"name":             "如何更改信用卡、密碼或送貨地址？",
						"title":            "如何更改信用卡、密碼或送貨地址？",
						"body":             `<p>登入您的帳號並前往右上角的個人資料圖示。在下拉式選單中選擇「設定」來編輯您的資料。</p>`,
						"locale":           "zh-tw",
					},
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115015959148,
						"author_id":        24400224208,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         0,
						"vote_sum":         -1,
						"vote_count":       1,
						"created_at":       time.Date(2017, 12, 27, 2, 59, 48, 0, time.UTC),
						"updated_at":       time.Date(2018, 3, 2, 5, 59, 58, 0, time.UTC),
						"source_locale":    "zh-tw",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2017, 12, 27, 3, 6, 54, 0, time.UTC),
						"label_names":      []string{},
						"country_code":     "tw",
						"url":              "https://honestbeehelp-tw.zendesk.com/api/v2/help_center/zh-tw/articles/115015959148-%E6%95%91%E5%91%BD-%E6%88%91%E5%BF%98%E8%A8%98%E5%AF%86%E7%A2%BC%E4%BA%86.json",
						"html_url":         "https://help.honestbee.tw/hc/zh-tw/articles/115015959148-%E6%95%91%E5%91%BD-%E6%88%91%E5%BF%98%E8%A8%98%E5%AF%86%E7%A2%BC%E4%BA%86",
						"name":             "救命！我忘記密碼了",
						"title":            "救命！我忘記密碼了",
						"body":             "<p>請在登入頁面點選「忘記密碼」，並輸入您註冊時所使用的電子信箱。我們會寄給您一封信讓您重設密碼。有時候信件會跑到垃圾信件匣，請務必檢查看看。</p>",
						"locale":           "zh-tw",
					},
				},
				"page":       1,
				"per_page":   30,
				"page_count": 1,
				"count":      5,
			},
		},
		{
			description: "testing not exist locale case",
			addr:        "/api/sections/115004118448/articles",
			args: url.Values{
				"locale":       {"not-exist-locale"},
				"country_code": {"tw"},
			},
			expectStatus: http.StatusBadRequest,
			expect: map[string]interface{}{
				"error": errs.InvalidAttributeErrorMsg,
			},
		},
		{
			description: "testing not exist country code case",
			addr:        "/api/sections/115004118448/articles",
			args: url.Values{
				"locale":       {"zh-tw"},
				"country_code": {"not-exist-country-code"},
			},
			expectStatus: http.StatusBadRequest,
			expect: map[string]interface{}{
				"error": errs.InvalidAttributeErrorMsg,
			},
		},
		{
			description: "testing not exist country code and locale case",
			addr:        "/api/sections/115004118448/articles",
			args: url.Values{
				"locale":       {"not-exist-locale"},
				"country_code": {"not-exist-country-code"},
			},
			expectStatus: http.StatusBadRequest,
			expect: map[string]interface{}{
				"error": errs.InvalidAttributeErrorMsg,
			},
		},
		{
			description: "testing not 0 per page case",
			addr:        "/api/sections/115004118448/articles",
			args: url.Values{
				"locale":       {"en-us"},
				"country_code": {"tw"},
				"per_page":     {"0"},
			},
			expectStatus: http.StatusBadRequest,
			expect: map[string]interface{}{
				"error": errs.InvalidAttributeErrorMsg,
			},
		},
		{
			description: "testing not 0 page case",
			addr:        "/api/sections/115004118448/articles",
			args: url.Values{
				"locale":       {"en-us"},
				"country_code": {"tw"},
				"page":         {"0"},
			},
			expectStatus: http.StatusBadRequest,
			expect: map[string]interface{}{
				"error": errs.InvalidAttributeErrorMsg,
			},
		},
		{
			description: "testing not 0 page and 0 per page case",
			addr:        "/api/sections/115004118448/articles",
			args: url.Values{
				"locale":       {"en-us"},
				"country_code": {"tw"},
				"page":         {"0"},
				"per_page":     {"0"},
			},
			expectStatus: http.StatusBadRequest,
			expect: map[string]interface{}{
				"error": errs.InvalidAttributeErrorMsg,
			},
		},
		{
			description: "testing sort by not correct case",
			addr:        "/api/sections/115004118448/articles",
			args: url.Values{
				"locale":       {"en-us"},
				"country_code": {"tw"},
				"sort_by":      {"unknown-sort-by"},
			},
			expectStatus: http.StatusBadRequest,
			expect: map[string]interface{}{
				"error": errs.InvalidAttributeErrorMsg,
			},
		},
		{
			description: "testing sort order not correct case",
			addr:        "/api/sections/115004118448/articles",
			args: url.Values{
				"locale":       {"en-us"},
				"country_code": {"tw"},
				"sort_order":   {"unknown-sort-order"},
			},
			expectStatus: http.StatusBadRequest,
			expect: map[string]interface{}{
				"error": errs.InvalidAttributeErrorMsg,
			},
		},
		{
			description: "testing sort by created at case",
			addr:        "/api/sections/115004118448/articles",
			args: url.Values{
				"locale":       {"en-us"},
				"country_code": {"tw"},
				"sort_by":      {"created_at"},
			},
			expectStatus: http.StatusOK,
			expect: map[string]interface{}{
				"articles": []interface{}{
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115015959148,
						"author_id":        24400224208,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         0,
						"vote_sum":         -1,
						"vote_count":       1,
						"created_at":       time.Date(2017, 12, 27, 2, 59, 48, 0, time.UTC),
						"updated_at":       time.Date(2018, 3, 2, 5, 59, 58, 0, time.UTC),
						"source_locale":    "zh-tw",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2017, 12, 27, 3, 6, 54, 0, time.UTC),
						"label_names":      []string{},
						"country_code":     "tw",
						"url":              "https://honestbeehelp-tw.zendesk.com/api/v2/help_center/en-us/articles/115015959148-Help-I-ve-forgotten-my-password-.json",
						"html_url":         "https://help.honestbee.tw/hc/en-us/articles/115015959148-Help-I-ve-forgotten-my-password-",
						"name":             "Help! I’ve forgotten my password.",
						"title":            "Help! I’ve forgotten my password.",
						"body":             "<p>Click on the Forgot Password link on the Login page and enter your registered email address. We’ll send you an email to reset your password. Occasionally emails end up in the junk/spam folder. Take a look there.</p>",
						"locale":           "en-us",
					},
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115015959168,
						"author_id":        24400224208,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         0,
						"vote_sum":         -2,
						"vote_count":       -2,
						"created_at":       time.Date(2017, 12, 27, 3, 8, 5, 0, time.UTC),
						"updated_at":       time.Date(2018, 3, 6, 12, 39, 30, 0, time.UTC),
						"source_locale":    "zh-tw",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2018, 1, 10, 6, 7, 41, 0, time.UTC),
						"label_names":      []string{},
						"country_code":     "tw",
						"url":              "https://honestbeehelp-tw.zendesk.com/api/v2/help_center/en-us/articles/115015959168-How-can-I-change-my-credit-card-password-or-delivery-address-.json",
						"html_url":         "https://help.honestbee.tw/hc/en-us/articles/115015959168-How-can-I-change-my-credit-card-password-or-delivery-address-",
						"name":             "How can I change my credit card,password or delivery address?",
						"title":            "How can I change my credit card,password or delivery address?",
						"body":             `<p>Log in to your account and go to your profile icon at the top right corner. Select Settings from the dropdown menu to edit your details.</p>`,
						"locale":           "en-us",
					},
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115015885507,
						"author_id":        24400224208,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         0,
						"vote_sum":         0,
						"vote_count":       0,
						"created_at":       time.Date(2017, 12, 27, 3, 11, 30, 0, time.UTC),
						"updated_at":       time.Date(2018, 1, 10, 6, 7, 41, 0, time.UTC),
						"source_locale":    "zh-tw",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2018, 1, 10, 6, 7, 41, 0, time.UTC),
						"label_names":      []string{},
						"country_code":     "tw",
						"url":              "https://honestbeehelp-tw.zendesk.com/api/v2/help_center/en-us/articles/115015885507-How-can-I-change-my-email-address-.json",
						"html_url":         "https://help.honestbee.tw/hc/en-us/articles/115015885507-How-can-I-change-my-email-address-",
						"name":             "How can I change my email address?",
						"title":            "How can I change my email address?",
						"body":             `<p>Currently,it’s not possible to change your email address. To register with a different email address,please create a new account.</p>`,
						"locale":           "en-us",
					},
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115015885547,
						"author_id":        24400224208,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         0,
						"vote_sum":         0,
						"vote_count":       0,
						"created_at":       time.Date(2017, 12, 27, 3, 12, 58, 0, time.UTC),
						"updated_at":       time.Date(2017, 12, 27, 3, 13, 42, 0, time.UTC),
						"source_locale":    "zh-tw",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2017, 12, 27, 3, 12, 58, 0, time.UTC),
						"label_names":      []string{},
						"country_code":     "tw",
						"url":              "https://honestbeehelp-tw.zendesk.com/api/v2/help_center/en-us/articles/115015885547-What-is-honestbee-s-information-security-policy-.json",
						"html_url":         "https://help.honestbee.tw/hc/en-us/articles/115015885547-What-is-honestbee-s-information-security-policy-",
						"name":             "What is honestbee’s information security policy?",
						"title":            "What is honestbee’s information security policy?",
						"body":             `<p>honestbee takes your privacy seriously and complies with all the relevant laws to ensure your details are kept secure. Read our <a href="https://www.honestbee.tw/privacy-policy">Privacy Policy</a> for more information.</p>`,
						"locale":           "en-us",
					},
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115015959188,
						"author_id":        24400224208,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         0,
						"vote_sum":         0,
						"vote_count":       0,
						"created_at":       time.Date(2017, 12, 27, 3, 14, 16, 0, time.UTC),
						"updated_at":       time.Date(2017, 12, 27, 3, 14, 48, 0, time.UTC),
						"source_locale":    "zh-tw",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2017, 12, 27, 3, 14, 16, 0, time.UTC),
						"label_names":      []string{},
						"country_code":     "tw",
						"url":              "https://honestbeehelp-tw.zendesk.com/api/v2/help_center/en-us/articles/115015959188-What-can-I-do-when-my-cart-is-locked-.json",
						"html_url":         "https://help.honestbee.tw/hc/en-us/articles/115015959188-What-can-I-do-when-my-cart-is-locked-",
						"name":             "What can I do when my cart is locked?",
						"title":            "What can I do when my cart is locked?",
						"body":             "<p>When there is an error completing your checkout,your cart will be temporarily locked to prevent further changes to your order. To unlock your cart,click ‘Yes,unlock my cart,’ when prompted.</p>",
						"locale":           "en-us",
					},
				},
				"page":       1,
				"per_page":   30,
				"page_count": 1,
				"count":      5,
			},
		},
		{
			description: "testing sort by updated at case",
			addr:        "/api/sections/115004118448/articles",
			args: url.Values{
				"locale":       {"en-us"},
				"country_code": {"tw"},
				"sort_by":      {"updated_at"},
			},
			expectStatus: http.StatusOK,
			expect: map[string]interface{}{
				"articles": []interface{}{
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115015885547,
						"author_id":        24400224208,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         0,
						"vote_sum":         0,
						"vote_count":       0,
						"created_at":       time.Date(2017, 12, 27, 3, 12, 58, 0, time.UTC),
						"updated_at":       time.Date(2017, 12, 27, 3, 13, 42, 0, time.UTC),
						"source_locale":    "zh-tw",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2017, 12, 27, 3, 12, 58, 0, time.UTC),
						"label_names":      []string{},
						"country_code":     "tw",
						"url":              "https://honestbeehelp-tw.zendesk.com/api/v2/help_center/en-us/articles/115015885547-What-is-honestbee-s-information-security-policy-.json",
						"html_url":         "https://help.honestbee.tw/hc/en-us/articles/115015885547-What-is-honestbee-s-information-security-policy-",
						"name":             "What is honestbee’s information security policy?",
						"title":            "What is honestbee’s information security policy?",
						"body":             `<p>honestbee takes your privacy seriously and complies with all the relevant laws to ensure your details are kept secure. Read our <a href="https://www.honestbee.tw/privacy-policy">Privacy Policy</a> for more information.</p>`,
						"locale":           "en-us",
					},
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115015959188,
						"author_id":        24400224208,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         0,
						"vote_sum":         0,
						"vote_count":       0,
						"created_at":       time.Date(2017, 12, 27, 3, 14, 16, 0, time.UTC),
						"updated_at":       time.Date(2017, 12, 27, 3, 14, 48, 0, time.UTC),
						"source_locale":    "zh-tw",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2017, 12, 27, 3, 14, 16, 0, time.UTC),
						"label_names":      []string{},
						"country_code":     "tw",
						"url":              "https://honestbeehelp-tw.zendesk.com/api/v2/help_center/en-us/articles/115015959188-What-can-I-do-when-my-cart-is-locked-.json",
						"html_url":         "https://help.honestbee.tw/hc/en-us/articles/115015959188-What-can-I-do-when-my-cart-is-locked-",
						"name":             "What can I do when my cart is locked?",
						"title":            "What can I do when my cart is locked?",
						"body":             "<p>When there is an error completing your checkout,your cart will be temporarily locked to prevent further changes to your order. To unlock your cart,click ‘Yes,unlock my cart,’ when prompted.</p>",
						"locale":           "en-us",
					},
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115015885507,
						"author_id":        24400224208,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         0,
						"vote_sum":         0,
						"vote_count":       0,
						"created_at":       time.Date(2017, 12, 27, 3, 11, 30, 0, time.UTC),
						"updated_at":       time.Date(2018, 1, 10, 6, 7, 41, 0, time.UTC),
						"source_locale":    "zh-tw",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2018, 1, 10, 6, 7, 41, 0, time.UTC),
						"label_names":      []string{},
						"country_code":     "tw",
						"url":              "https://honestbeehelp-tw.zendesk.com/api/v2/help_center/en-us/articles/115015885507-How-can-I-change-my-email-address-.json",
						"html_url":         "https://help.honestbee.tw/hc/en-us/articles/115015885507-How-can-I-change-my-email-address-",
						"name":             "How can I change my email address?",
						"title":            "How can I change my email address?",
						"body":             `<p>Currently,it’s not possible to change your email address. To register with a different email address,please create a new account.</p>`,
						"locale":           "en-us",
					},
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115015959148,
						"author_id":        24400224208,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         0,
						"vote_sum":         -1,
						"vote_count":       1,
						"created_at":       time.Date(2017, 12, 27, 2, 59, 48, 0, time.UTC),
						"updated_at":       time.Date(2018, 3, 2, 5, 59, 58, 0, time.UTC),
						"source_locale":    "zh-tw",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2017, 12, 27, 3, 6, 54, 0, time.UTC),
						"label_names":      []string{},
						"country_code":     "tw",
						"url":              "https://honestbeehelp-tw.zendesk.com/api/v2/help_center/en-us/articles/115015959148-Help-I-ve-forgotten-my-password-.json",
						"html_url":         "https://help.honestbee.tw/hc/en-us/articles/115015959148-Help-I-ve-forgotten-my-password-",
						"name":             "Help! I’ve forgotten my password.",
						"title":            "Help! I’ve forgotten my password.",
						"body":             "<p>Click on the Forgot Password link on the Login page and enter your registered email address. We’ll send you an email to reset your password. Occasionally emails end up in the junk/spam folder. Take a look there.</p>",
						"locale":           "en-us",
					},
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115015959168,
						"author_id":        24400224208,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         0,
						"vote_sum":         -2,
						"vote_count":       -2,
						"created_at":       time.Date(2017, 12, 27, 3, 8, 5, 0, time.UTC),
						"updated_at":       time.Date(2018, 3, 6, 12, 39, 30, 0, time.UTC),
						"source_locale":    "zh-tw",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2018, 1, 10, 6, 7, 41, 0, time.UTC),
						"label_names":      []string{},
						"country_code":     "tw",
						"url":              "https://honestbeehelp-tw.zendesk.com/api/v2/help_center/en-us/articles/115015959168-How-can-I-change-my-credit-card-password-or-delivery-address-.json",
						"html_url":         "https://help.honestbee.tw/hc/en-us/articles/115015959168-How-can-I-change-my-credit-card-password-or-delivery-address-",
						"name":             "How can I change my credit card,password or delivery address?",
						"title":            "How can I change my credit card,password or delivery address?",
						"body":             `<p>Log in to your account and go to your profile icon at the top right corner. Select Settings from the dropdown menu to edit your details.</p>`,
						"locale":           "en-us",
					},
				},
				"page":       1,
				"per_page":   30,
				"page_count": 1,
				"count":      5,
			},
		},
		{
			description: "testing sort order desc with order by updated at case",
			addr:        "/api/sections/115004118448/articles",
			args: url.Values{
				"locale":       {"en-us"},
				"country_code": {"tw"},
				"sort_by":      {"updated_at"},
				"sort_order":   {"desc"},
			},
			expectStatus: http.StatusOK,
			expect: map[string]interface{}{
				"articles": []interface{}{
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115015959168,
						"author_id":        24400224208,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         0,
						"vote_sum":         -2,
						"vote_count":       -2,
						"created_at":       time.Date(2017, 12, 27, 3, 8, 5, 0, time.UTC),
						"updated_at":       time.Date(2018, 3, 6, 12, 39, 30, 0, time.UTC),
						"source_locale":    "zh-tw",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2018, 1, 10, 6, 7, 41, 0, time.UTC),
						"label_names":      []string{},
						"country_code":     "tw",
						"url":              "https://honestbeehelp-tw.zendesk.com/api/v2/help_center/en-us/articles/115015959168-How-can-I-change-my-credit-card-password-or-delivery-address-.json",
						"html_url":         "https://help.honestbee.tw/hc/en-us/articles/115015959168-How-can-I-change-my-credit-card-password-or-delivery-address-",
						"name":             "How can I change my credit card,password or delivery address?",
						"title":            "How can I change my credit card,password or delivery address?",
						"body":             `<p>Log in to your account and go to your profile icon at the top right corner. Select Settings from the dropdown menu to edit your details.</p>`,
						"locale":           "en-us",
					},
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115015959148,
						"author_id":        24400224208,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         0,
						"vote_sum":         -1,
						"vote_count":       1,
						"created_at":       time.Date(2017, 12, 27, 2, 59, 48, 0, time.UTC),
						"updated_at":       time.Date(2018, 3, 2, 5, 59, 58, 0, time.UTC),
						"source_locale":    "zh-tw",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2017, 12, 27, 3, 6, 54, 0, time.UTC),
						"label_names":      []string{},
						"country_code":     "tw",
						"url":              "https://honestbeehelp-tw.zendesk.com/api/v2/help_center/en-us/articles/115015959148-Help-I-ve-forgotten-my-password-.json",
						"html_url":         "https://help.honestbee.tw/hc/en-us/articles/115015959148-Help-I-ve-forgotten-my-password-",
						"name":             "Help! I’ve forgotten my password.",
						"title":            "Help! I’ve forgotten my password.",
						"body":             "<p>Click on the Forgot Password link on the Login page and enter your registered email address. We’ll send you an email to reset your password. Occasionally emails end up in the junk/spam folder. Take a look there.</p>",
						"locale":           "en-us",
					},
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115015885507,
						"author_id":        24400224208,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         0,
						"vote_sum":         0,
						"vote_count":       0,
						"created_at":       time.Date(2017, 12, 27, 3, 11, 30, 0, time.UTC),
						"updated_at":       time.Date(2018, 1, 10, 6, 7, 41, 0, time.UTC),
						"source_locale":    "zh-tw",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2018, 1, 10, 6, 7, 41, 0, time.UTC),
						"label_names":      []string{},
						"country_code":     "tw",
						"url":              "https://honestbeehelp-tw.zendesk.com/api/v2/help_center/en-us/articles/115015885507-How-can-I-change-my-email-address-.json",
						"html_url":         "https://help.honestbee.tw/hc/en-us/articles/115015885507-How-can-I-change-my-email-address-",
						"name":             "How can I change my email address?",
						"title":            "How can I change my email address?",
						"body":             `<p>Currently,it’s not possible to change your email address. To register with a different email address,please create a new account.</p>`,
						"locale":           "en-us",
					},
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115015959188,
						"author_id":        24400224208,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         0,
						"vote_sum":         0,
						"vote_count":       0,
						"created_at":       time.Date(2017, 12, 27, 3, 14, 16, 0, time.UTC),
						"updated_at":       time.Date(2017, 12, 27, 3, 14, 48, 0, time.UTC),
						"source_locale":    "zh-tw",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2017, 12, 27, 3, 14, 16, 0, time.UTC),
						"label_names":      []string{},
						"country_code":     "tw",
						"url":              "https://honestbeehelp-tw.zendesk.com/api/v2/help_center/en-us/articles/115015959188-What-can-I-do-when-my-cart-is-locked-.json",
						"html_url":         "https://help.honestbee.tw/hc/en-us/articles/115015959188-What-can-I-do-when-my-cart-is-locked-",
						"name":             "What can I do when my cart is locked?",
						"title":            "What can I do when my cart is locked?",
						"body":             "<p>When there is an error completing your checkout,your cart will be temporarily locked to prevent further changes to your order. To unlock your cart,click ‘Yes,unlock my cart,’ when prompted.</p>",
						"locale":           "en-us",
					},
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115015885547,
						"author_id":        24400224208,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         0,
						"vote_sum":         0,
						"vote_count":       0,
						"created_at":       time.Date(2017, 12, 27, 3, 12, 58, 0, time.UTC),
						"updated_at":       time.Date(2017, 12, 27, 3, 13, 42, 0, time.UTC),
						"source_locale":    "zh-tw",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2017, 12, 27, 3, 12, 58, 0, time.UTC),
						"label_names":      []string{},
						"country_code":     "tw",
						"url":              "https://honestbeehelp-tw.zendesk.com/api/v2/help_center/en-us/articles/115015885547-What-is-honestbee-s-information-security-policy-.json",
						"html_url":         "https://help.honestbee.tw/hc/en-us/articles/115015885547-What-is-honestbee-s-information-security-policy-",
						"name":             "What is honestbee’s information security policy?",
						"title":            "What is honestbee’s information security policy?",
						"body":             `<p>honestbee takes your privacy seriously and complies with all the relevant laws to ensure your details are kept secure. Read our <a href="https://www.honestbee.tw/privacy-policy">Privacy Policy</a> for more information.</p>`,
						"locale":           "en-us",
					},
				},
				"page":       1,
				"per_page":   30,
				"page_count": 1,
				"count":      5,
			},
		},
		{
			description: "testing per page 2 case",
			addr:        "/api/sections/115004118448/articles",
			args: url.Values{
				"locale":       {"en-us"},
				"country_code": {"tw"},
				"per_page":     {"2"},
			},
			expectStatus: http.StatusOK,
			expect: map[string]interface{}{
				"articles": []interface{}{
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115015959188,
						"author_id":        24400224208,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         0,
						"vote_sum":         0,
						"vote_count":       0,
						"created_at":       time.Date(2017, 12, 27, 3, 14, 16, 0, time.UTC),
						"updated_at":       time.Date(2017, 12, 27, 3, 14, 48, 0, time.UTC),
						"source_locale":    "zh-tw",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2017, 12, 27, 3, 14, 16, 0, time.UTC),
						"label_names":      []string{},
						"country_code":     "tw",
						"url":              "https://honestbeehelp-tw.zendesk.com/api/v2/help_center/en-us/articles/115015959188-What-can-I-do-when-my-cart-is-locked-.json",
						"html_url":         "https://help.honestbee.tw/hc/en-us/articles/115015959188-What-can-I-do-when-my-cart-is-locked-",
						"name":             "What can I do when my cart is locked?",
						"title":            "What can I do when my cart is locked?",
						"body":             "<p>When there is an error completing your checkout,your cart will be temporarily locked to prevent further changes to your order. To unlock your cart,click ‘Yes,unlock my cart,’ when prompted.</p>",
						"locale":           "en-us",
					},
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115015885547,
						"author_id":        24400224208,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         0,
						"vote_sum":         0,
						"vote_count":       0,
						"created_at":       time.Date(2017, 12, 27, 3, 12, 58, 0, time.UTC),
						"updated_at":       time.Date(2017, 12, 27, 3, 13, 42, 0, time.UTC),
						"source_locale":    "zh-tw",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2017, 12, 27, 3, 12, 58, 0, time.UTC),
						"label_names":      []string{},
						"country_code":     "tw",
						"url":              "https://honestbeehelp-tw.zendesk.com/api/v2/help_center/en-us/articles/115015885547-What-is-honestbee-s-information-security-policy-.json",
						"html_url":         "https://help.honestbee.tw/hc/en-us/articles/115015885547-What-is-honestbee-s-information-security-policy-",
						"name":             "What is honestbee’s information security policy?",
						"title":            "What is honestbee’s information security policy?",
						"body":             `<p>honestbee takes your privacy seriously and complies with all the relevant laws to ensure your details are kept secure. Read our <a href="https://www.honestbee.tw/privacy-policy">Privacy Policy</a> for more information.</p>`,
						"locale":           "en-us",
					},
				},
				"page":       1,
				"per_page":   2,
				"page_count": 3,
				"count":      5,
			},
		},
		{
			description: "testing per page 2 page 2 case",
			addr:        "/api/sections/115004118448/articles",
			args: url.Values{
				"locale":       {"en-us"},
				"country_code": {"tw"},
				"page":         {"2"},
				"per_page":     {"2"},
			},
			expectStatus: http.StatusOK,
			expect: map[string]interface{}{
				"articles": []interface{}{
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115015885507,
						"author_id":        24400224208,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         0,
						"vote_sum":         0,
						"vote_count":       0,
						"created_at":       time.Date(2017, 12, 27, 3, 11, 30, 0, time.UTC),
						"updated_at":       time.Date(2018, 1, 10, 6, 7, 41, 0, time.UTC),
						"source_locale":    "zh-tw",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2018, 1, 10, 6, 7, 41, 0, time.UTC),
						"label_names":      []string{},
						"country_code":     "tw",
						"url":              "https://honestbeehelp-tw.zendesk.com/api/v2/help_center/en-us/articles/115015885507-How-can-I-change-my-email-address-.json",
						"html_url":         "https://help.honestbee.tw/hc/en-us/articles/115015885507-How-can-I-change-my-email-address-",
						"name":             "How can I change my email address?",
						"title":            "How can I change my email address?",
						"body":             `<p>Currently,it’s not possible to change your email address. To register with a different email address,please create a new account.</p>`,
						"locale":           "en-us",
					},
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115015959168,
						"author_id":        24400224208,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         0,
						"vote_sum":         -2,
						"vote_count":       -2,
						"created_at":       time.Date(2017, 12, 27, 3, 8, 5, 0, time.UTC),
						"updated_at":       time.Date(2018, 3, 6, 12, 39, 30, 0, time.UTC),
						"source_locale":    "zh-tw",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2018, 1, 10, 6, 7, 41, 0, time.UTC),
						"label_names":      []string{},
						"country_code":     "tw",
						"url":              "https://honestbeehelp-tw.zendesk.com/api/v2/help_center/en-us/articles/115015959168-How-can-I-change-my-credit-card-password-or-delivery-address-.json",
						"html_url":         "https://help.honestbee.tw/hc/en-us/articles/115015959168-How-can-I-change-my-credit-card-password-or-delivery-address-",
						"name":             "How can I change my credit card,password or delivery address?",
						"title":            "How can I change my credit card,password or delivery address?",
						"body":             `<p>Log in to your account and go to your profile icon at the top right corner. Select Settings from the dropdown menu to edit your details.</p>`,
						"locale":           "en-us",
					},
				},
				"page":       2,
				"per_page":   2,
				"page_count": 3,
				"count":      5,
			},
		},
		{
			description: "testing per page 2 page 3 case",
			addr:        "/api/sections/115004118448/articles",
			args: url.Values{
				"locale":       {"en-us"},
				"country_code": {"tw"},
				"page":         {"3"},
				"per_page":     {"2"},
			},
			expectStatus: http.StatusOK,
			expect: map[string]interface{}{
				"articles": []interface{}{
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115015959148,
						"author_id":        24400224208,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         0,
						"vote_sum":         -1,
						"vote_count":       1,
						"created_at":       time.Date(2017, 12, 27, 2, 59, 48, 0, time.UTC),
						"updated_at":       time.Date(2018, 3, 2, 5, 59, 58, 0, time.UTC),
						"source_locale":    "zh-tw",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2017, 12, 27, 3, 6, 54, 0, time.UTC),
						"label_names":      []string{},
						"country_code":     "tw",
						"url":              "https://honestbeehelp-tw.zendesk.com/api/v2/help_center/en-us/articles/115015959148-Help-I-ve-forgotten-my-password-.json",
						"html_url":         "https://help.honestbee.tw/hc/en-us/articles/115015959148-Help-I-ve-forgotten-my-password-",
						"name":             "Help! I’ve forgotten my password.",
						"title":            "Help! I’ve forgotten my password.",
						"body":             "<p>Click on the Forgot Password link on the Login page and enter your registered email address. We’ll send you an email to reset your password. Occasionally emails end up in the junk/spam folder. Take a look there.</p>",
						"locale":           "en-us",
					},
				},
				"page":       3,
				"per_page":   2,
				"page_count": 3,
				"count":      5,
			},
		},
	}

	for _, tt := range testCases {
		t.Run(tt.description, func(t *testing.T) {
			resp, err := ts.Client().Get(ts.URL + tt.addr + "?" + tt.args.Encode())
			if err != nil {
				t.Fatalf("[%s] http client do failed:%v", tt.description, err)
			}
			defer resp.Body.Close()

			if tt.expectStatus != resp.StatusCode {
				t.Errorf("[%s] http status expect:%v != actual:%v", tt.description, tt.expectStatus, resp.Status)
			}

			actual := make(map[string]interface{})
			if err = json.NewDecoder(resp.Body).Decode(&actual); err != nil {
				t.Fatalf("[%s] json decoding failed:%v", tt.description, err)
			}
			expectData, err := json.Marshal(tt.expect)
			if err != nil {
				t.Fatalf("[%s] json marshal failed:%v", tt.description, err)
			}
			expect := make(map[string]interface{})
			if err = json.Unmarshal(expectData, &expect); err != nil {
				t.Fatalf("[%s] json unmarshal failed:%v", tt.description, err)
			}
			if diff := deep.Equal(expect, actual); diff != nil {
				t.Errorf("[%s] %v", tt.description, diff)
			}
		})
	}
}

func TestHandlersArticle(t *testing.T) {
	ts := newTserver()
	defer ts.closeAll()
	testCases := []struct {
		description  string
		args         url.Values
		addr         string
		expect       map[string]interface{}
		expectStatus int
	}{
		{
			description: "testing normal en-us locale case",
			addr:        "/api/articles/115015959188",
			args: url.Values{
				"locale":       {"en-us"},
				"country_code": {"tw"},
			},
			expectStatus: http.StatusOK,
			expect: map[string]interface{}{
				"article": map[string]interface{}{
					"section_id":       115004118448,
					"id":               115015959188,
					"author_id":        24400224208,
					"comments_disable": false,
					"draft":            false,
					"promoted":         false,
					"position":         0,
					"vote_sum":         0,
					"vote_count":       0,
					"created_at":       time.Date(2017, 12, 27, 3, 14, 16, 0, time.UTC),
					"updated_at":       time.Date(2017, 12, 27, 3, 14, 48, 0, time.UTC),
					"source_locale":    "zh-tw",
					"outdated":         false,
					"outdated_locales": []string{},
					"edited_at":        time.Date(2017, 12, 27, 3, 14, 16, 0, time.UTC),
					"label_names":      []string{},
					"country_code":     "tw",
					"url":              "https://honestbeehelp-tw.zendesk.com/api/v2/help_center/en-us/articles/115015959188-What-can-I-do-when-my-cart-is-locked-.json",
					"html_url":         "https://help.honestbee.tw/hc/en-us/articles/115015959188-What-can-I-do-when-my-cart-is-locked-",
					"name":             "What can I do when my cart is locked?",
					"title":            "What can I do when my cart is locked?",
					"body":             "<p>When there is an error completing your checkout,your cart will be temporarily locked to prevent further changes to your order. To unlock your cart,click ‘Yes,unlock my cart,’ when prompted.</p>",
					"locale":           "en-us",
				},
			},
		},
		{
			description: "testing normal zh-tw locale case",
			addr:        "/api/articles/115015959188",
			args: url.Values{
				"locale":       {"zh-tw"},
				"country_code": {"tw"},
			},
			expectStatus: http.StatusOK,
			expect: map[string]interface{}{
				"article": map[string]interface{}{
					"section_id":       115004118448,
					"id":               115015959188,
					"author_id":        24400224208,
					"comments_disable": false,
					"draft":            false,
					"promoted":         false,
					"position":         0,
					"vote_sum":         0,
					"vote_count":       0,
					"created_at":       time.Date(2017, 12, 27, 3, 14, 16, 0, time.UTC),
					"updated_at":       time.Date(2017, 12, 27, 3, 14, 48, 0, time.UTC),
					"source_locale":    "zh-tw",
					"outdated":         false,
					"outdated_locales": []string{},
					"edited_at":        time.Date(2017, 12, 27, 3, 14, 16, 0, time.UTC),
					"label_names":      []string{},
					"country_code":     "tw",
					"url":              "https://honestbeehelp-tw.zendesk.com/api/v2/help_center/zh-tw/articles/115015959188-%E6%88%91%E7%9A%84%E8%B3%BC%E7%89%A9%E8%BB%8A%E9%8E%96%E4%BD%8F%E4%BA%86-%E8%A9%B2%E6%80%8E%E9%BA%BC%E8%BE%A6-.json",
					"html_url":         "https://help.honestbee.tw/hc/zh-tw/articles/115015959188-%E6%88%91%E7%9A%84%E8%B3%BC%E7%89%A9%E8%BB%8A%E9%8E%96%E4%BD%8F%E4%BA%86-%E8%A9%B2%E6%80%8E%E9%BA%BC%E8%BE%A6-",
					"name":             "我的購物車鎖住了，該怎麼辦？",
					"title":            "我的購物車鎖住了，該怎麼辦？",
					"body":             "<p>當結帳出現錯誤時，您的購物車會暫時被鎖住，以避免您的訂單出現異動。要解鎖您的購物車，請在出現提示時，點選「是的，解鎖我的購物車」。</p>",
					"locale":           "zh-tw",
				},
			},
		},
		{
			description: "testing article id not exist case",
			addr:        "/api/articles/334567833",
			args: url.Values{
				"locale":       {"zh-tw"},
				"country_code": {"tw"},
			},
			expectStatus: http.StatusNotFound,
			expect: map[string]interface{}{
				"error": errs.RecordNotFoundErrorMsg,
			},
		},
	}

	for _, tt := range testCases {
		t.Run(tt.description, func(t *testing.T) {
			resp, err := ts.Client().Get(ts.URL + tt.addr + "?" + tt.args.Encode())
			if err != nil {
				t.Fatalf("[%s] http client do failed:%v", tt.description, err)
			}
			defer resp.Body.Close()

			if tt.expectStatus != resp.StatusCode {
				t.Errorf("[%s] http status expect:%v != actual:%v", tt.description, tt.expectStatus, resp.Status)
			}

			actual := make(map[string]interface{})
			if err = json.NewDecoder(resp.Body).Decode(&actual); err != nil {
				t.Fatalf("[%s] json decoding failed:%v", tt.description, err)
			}
			expectData, err := json.Marshal(tt.expect)
			if err != nil {
				t.Fatalf("[%s] json marshal failed:%v", tt.description, err)
			}
			expect := make(map[string]interface{})
			if err = json.Unmarshal(expectData, &expect); err != nil {
				t.Fatalf("[%s] json unmarshal failed:%v", tt.description, err)
			}
			if diff := deep.Equal(expect, actual); diff != nil {
				t.Errorf("[%s] %v", tt.description, diff)
			}
		})
	}
}
