// +build integration

package integration

import (
	"encoding/json"
	"net/http"
	"net/url"
	"testing"
	"time"

	"github.com/go-test/deep"

	"github.com/honestbee/Zen/errs"
)

func TestHandlersCategories(t *testing.T) {
	ts := newTserver()
	defer ts.closeAll()
	testCases := []struct {
		description  string
		args         url.Values
		addr         string
		expect       map[string]interface{}
		expectStatus int
	}{
		{
			description: "testing normal en-us locale case",
			addr:        "/api/categories",
			args: url.Values{
				"locale":       {"en-us"},
				"country_code": {"tw"},
			},
			expect: map[string]interface{}{
				"categories": []interface{}{
					map[string]interface{}{
						"id":            115002432448,
						"position":      2,
						"created_at":    time.Date(2017, 12, 19, 6, 21, 45, 0, time.UTC),
						"updated_at":    time.Date(2018, 3, 6, 12, 39, 30, 0, time.UTC),
						"source_locale": "en-us",
						"outdated":      false,
						"country_code":  "tw",
						"url":           "https://honestbeehelp-tw.zendesk.com/api/v2/help_center/en-us/categories/115002432448-My-Account.json",
						"html_url":      "https://help.honestbee.tw/hc/en-us/categories/115002432448-My-Account",
						"name":          "My Account",
						"description":   "",
						"locale":        "en-us",
						"key_name":      "myAccount",
					},
				},
				"page":       1,
				"per_page":   30,
				"page_count": 1,
				"count":      1,
			},
			expectStatus: http.StatusOK,
		},
		{
			description: "testing normal zh-tw locale case",
			addr:        "/api/categories",
			args: url.Values{
				"locale":       {"zh-tw"},
				"country_code": {"tw"},
			},
			expect: map[string]interface{}{
				"categories": []interface{}{
					map[string]interface{}{
						"id":            115002432448,
						"position":      2,
						"created_at":    time.Date(2017, 12, 19, 6, 21, 45, 0, time.UTC),
						"updated_at":    time.Date(2018, 3, 6, 12, 39, 30, 0, time.UTC),
						"source_locale": "en-us",
						"outdated":      false,
						"country_code":  "tw",
						"url":           "https://honestbeehelp-tw.zendesk.com/api/v2/help_center/zh-tw/categories/115002432448-%E6%88%91%E7%9A%84%E5%B8%B3%E8%99%9F.json",
						"html_url":      "https://help.honestbee.tw/hc/zh-tw/categories/115002432448-%E6%88%91%E7%9A%84%E5%B8%B3%E8%99%9F",
						"name":          "我的帳號",
						"description":   "",
						"locale":        "zh-tw",
						"key_name":      "myAccount",
					},
				},
				"page":       1,
				"per_page":   30,
				"page_count": 1,
				"count":      1,
			},
			expectStatus: http.StatusOK,
		},
		{
			description: "testing not exist locale case",
			addr:        "/api/categories",
			args: url.Values{
				"locale":       {"not-exist-locale"},
				"country_code": {"tw"},
			},
			expectStatus: http.StatusBadRequest,
			expect: map[string]interface{}{
				"error": errs.InvalidAttributeErrorMsg,
			},
		},
		{
			description: "testing not exist country code case",
			addr:        "/api/categories",
			args: url.Values{
				"locale":       {"zh-tw"},
				"country_code": {"not-exist-country-code"},
			},
			expectStatus: http.StatusBadRequest,
			expect: map[string]interface{}{
				"error": errs.InvalidAttributeErrorMsg,
			},
		},
		{
			description: "testing not exist country code and locale case",
			addr:        "/api/categories",
			args: url.Values{
				"locale":       {"not-exist-locale"},
				"country_code": {"not-exist-country-code"},
			},
			expectStatus: http.StatusBadRequest,
			expect: map[string]interface{}{
				"error": errs.InvalidAttributeErrorMsg,
			},
		},
		{
			description: "testing not 0 per page case",
			addr:        "/api/categories",
			args: url.Values{
				"locale":       {"en-us"},
				"country_code": {"tw"},
				"per_page":     {"0"},
			},
			expectStatus: http.StatusBadRequest,
			expect: map[string]interface{}{
				"error": errs.InvalidAttributeErrorMsg,
			},
		},
		{
			description: "testing not 0 page case",
			addr:        "/api/categories",
			args: url.Values{
				"locale":       {"en-us"},
				"country_code": {"tw"},
				"page":         {"0"},
			},
			expectStatus: http.StatusBadRequest,
			expect: map[string]interface{}{
				"error": errs.InvalidAttributeErrorMsg,
			},
		},
		{
			description: "testing not 0 page and 0 per page case",
			addr:        "/api/categories",
			args: url.Values{
				"locale":       {"en-us"},
				"country_code": {"tw"},
				"page":         {"0"},
				"per_page":     {"0"},
			},
			expectStatus: http.StatusBadRequest,
			expect: map[string]interface{}{
				"error": errs.InvalidAttributeErrorMsg,
			},
		},
		{
			description: "testing sort by created at case",
			addr:        "/api/categories",
			args: url.Values{
				"locale":       {"en-us"},
				"country_code": {"tw"},
				"sort_by":      {"created_at"},
			},
			expectStatus: http.StatusOK,
			expect: map[string]interface{}{
				"categories": []interface{}{
					map[string]interface{}{
						"id":            115002432448,
						"position":      2,
						"created_at":    time.Date(2017, 12, 19, 6, 21, 45, 0, time.UTC),
						"updated_at":    time.Date(2018, 3, 6, 12, 39, 30, 0, time.UTC),
						"source_locale": "en-us",
						"outdated":      false,
						"country_code":  "tw",
						"url":           "https://honestbeehelp-tw.zendesk.com/api/v2/help_center/en-us/categories/115002432448-My-Account.json",
						"html_url":      "https://help.honestbee.tw/hc/en-us/categories/115002432448-My-Account",
						"name":          "My Account",
						"description":   "",
						"locale":        "en-us",
						"key_name":      "myAccount",
					},
				},
				"page":       1,
				"per_page":   30,
				"page_count": 1,
				"count":      1,
			},
		},
		{
			description: "testing sort by updated at case",
			addr:        "/api/categories",
			args: url.Values{
				"locale":       {"en-us"},
				"country_code": {"tw"},
				"sort_by":      {"updated_at"},
			},
			expectStatus: http.StatusOK,
			expect: map[string]interface{}{
				"categories": []interface{}{
					map[string]interface{}{
						"id":            115002432448,
						"position":      2,
						"created_at":    time.Date(2017, 12, 19, 6, 21, 45, 0, time.UTC),
						"updated_at":    time.Date(2018, 3, 6, 12, 39, 30, 0, time.UTC),
						"source_locale": "en-us",
						"outdated":      false,
						"country_code":  "tw",
						"url":           "https://honestbeehelp-tw.zendesk.com/api/v2/help_center/en-us/categories/115002432448-My-Account.json",
						"html_url":      "https://help.honestbee.tw/hc/en-us/categories/115002432448-My-Account",
						"name":          "My Account",
						"description":   "",
						"locale":        "en-us",
						"key_name":      "myAccount",
					},
				},
				"page":       1,
				"per_page":   30,
				"page_count": 1,
				"count":      1,
			},
		},
		{
			description: "testing sort by not correct case",
			addr:        "/api/categories",
			args: url.Values{
				"locale":       {"en-us"},
				"country_code": {"tw"},
				"sort_by":      {"unknown-sort-by"},
			},
			expectStatus: http.StatusBadRequest,
			expect: map[string]interface{}{
				"error": errs.InvalidAttributeErrorMsg,
			},
		},
		{
			description: "testing sort order desc case",
			addr:        "/api/categories",
			args: url.Values{
				"locale":       {"en-us"},
				"country_code": {"tw"},
				"sort_order":   {"desc"},
			},
			expectStatus: http.StatusOK,
			expect: map[string]interface{}{
				"categories": []interface{}{
					map[string]interface{}{
						"id":            115002432448,
						"position":      2,
						"created_at":    time.Date(2017, 12, 19, 6, 21, 45, 0, time.UTC),
						"updated_at":    time.Date(2018, 3, 6, 12, 39, 30, 0, time.UTC),
						"source_locale": "en-us",
						"outdated":      false,
						"country_code":  "tw",
						"url":           "https://honestbeehelp-tw.zendesk.com/api/v2/help_center/en-us/categories/115002432448-My-Account.json",
						"html_url":      "https://help.honestbee.tw/hc/en-us/categories/115002432448-My-Account",
						"name":          "My Account",
						"description":   "",
						"locale":        "en-us",
						"key_name":      "myAccount",
					},
				},
				"page":       1,
				"per_page":   30,
				"page_count": 1,
				"count":      1,
			},
		},
		{
			description: "testing sort order not correct case",
			addr:        "/api/categories",
			args: url.Values{
				"locale":       {"en-us"},
				"country_code": {"tw"},
				"sort_order":   {"unknown-sort-order"},
			},
			expectStatus: http.StatusBadRequest,
			expect: map[string]interface{}{
				"error": errs.InvalidAttributeErrorMsg,
			},
		},
	}

	for _, tt := range testCases {
		t.Run(tt.description, func(t *testing.T) {
			resp, err := ts.Client().Get(ts.URL + tt.addr + "?" + tt.args.Encode())
			if err != nil {
				t.Fatalf("[%s] http client do failed:%v", tt.description, err)
			}
			defer resp.Body.Close()

			if tt.expectStatus != resp.StatusCode {
				t.Errorf("[%s] http status expect:%v != actual:%v", tt.description, tt.expectStatus, resp.Status)
			}

			actual := make(map[string]interface{})
			if err = json.NewDecoder(resp.Body).Decode(&actual); err != nil {
				t.Fatalf("[%s] json decoding failed:%v", tt.description, err)
			}
			expectData, err := json.Marshal(tt.expect)
			if err != nil {
				t.Fatalf("[%s] json marshal failed:%v", tt.description, err)
			}
			expect := make(map[string]interface{})
			if err = json.Unmarshal(expectData, &expect); err != nil {
				t.Fatalf("[%s] json unmarshal failed:%v", tt.description, err)
			}
			if diff := deep.Equal(expect, actual); diff != nil {
				t.Errorf("[%s] %v", tt.description, diff)
			}
		})
	}
}

func TestHandlersCategoriesArticles(t *testing.T) {
	ts := newTserver()
	defer ts.closeAll()
	testCases := []struct {
		description  string
		args         url.Values
		addr         string
		expect       map[string]interface{}
		expectStatus int
	}{
		{
			description: "testing normal en-us locale case without label_names",
			addr:        "/api/categories/115002432448/articles",
			args: url.Values{
				"locale":       {"en-us"},
				"country_code": {"sg"},
			},
			expectStatus: http.StatusOK,
			expect: map[string]interface{}{
				"articles": []interface{}{
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115016053147,
						"author_id":        7222048487,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         0,
						"vote_sum":         17,
						"vote_count":       33,
						"created_at":       time.Date(2018, 01, 12, 3, 24, 59, 0, time.UTC),
						"updated_at":       time.Date(2018, 07, 16, 13, 35, 30, 0, time.UTC),
						"source_locale":    "en-us",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2018, 07, 10, 4, 17, 18, 0, time.UTC),
						"label_names":      []string{"use_for_answer_bot", "preparing", "ontheway", "confirmed"},
						"country_code":     "sg",
						"url":              "https://honestbeehelp-sg.zendesk.com/api/v2/help_center/en-us/articles/115016053147-How-do-I-prepare-my-laundry-for-pickup-.json",
						"html_url":         "https://honestbeehelp-sg.zendesk.com/hc/en-us/articles/115016053147-How-do-I-prepare-my-laundry-for-pickup-",
						"name":             "How do I prepare my laundry for pickup?",
						"title":            "How do I prepare my laundry for pickup?",
						"body":             "<p>Please be ready with your laundry when the delivery bee comes. Also check that all clothing pockets are empty, as it will be difficult for us to trace personal articles after your laundry has been handed over. We will not be liable for missing personal articles after you hand it over to us as well.</p>",
						"locale":           "en-us",
					},
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115016039687,
						"author_id":        7222048487,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         0,
						"vote_sum":         -1,
						"vote_count":       9,
						"created_at":       time.Date(2018, 01, 11, 11, 49, 48, 0, time.UTC),
						"updated_at":       time.Date(2018, 07, 10, 04, 17, 49, 0, time.UTC),
						"source_locale":    "en-us",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2018, 01, 11, 11, 49, 48, 0, time.UTC),
						"label_names":      []string{"delivered"},
						"country_code":     "sg",
						"url":              "https://honestbeehelp-sg.zendesk.com/api/v2/help_center/en-us/articles/115016039687-I-have-not-received-my-order-confirmation-final-receipt.json",
						"html_url":         "https://honestbeehelp-sg.zendesk.com/hc/en-us/articles/115016039687-I-have-not-received-my-order-confirmation-final-receipt",
						"name":             "I have not received my order confirmation/final receipt",
						"title":            "I have not received my order confirmation/final receipt",
						"body":             "<p>We send you your order confirmation immediately after you have placed an order. There is a chance that it might have ended up in the junk/spam folder. Please let us know if you do not find it there.</p>\\n<p><br>We aim to send you your final receipt within 5 working days after we have returned your laundry. Please note that we might adjust your final receipt for any additional articles added to the order and the difference in weight (if any) of your wash and fold loads.</p>\\n<p><br>If this answer did not solve your issue, please contact us and we will do our best to make things right for you. </p>",
						"locale":           "en-us",
					},
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115015447167,
						"author_id":        24400224208,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         0,
						"vote_sum":         0,
						"vote_count":       -30,
						"created_at":       time.Date(2017, 11, 29, 2, 37, 50, 0, time.UTC),
						"updated_at":       time.Date(2018, 07, 14, 10, 33, 44, 0, time.UTC),
						"source_locale":    "en-us",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2018, 07, 9, 9, 49, 23, 0, time.UTC),
						"label_names":      []string{"preparing", "confirmed"},
						"country_code":     "sg",
						"url":              "https://honestbeehelp-sg.zendesk.com/api/v2/help_center/en-us/articles/115015447167-I-want-to-cancel-my-food-order.json",
						"html_url":         "https://honestbeehelp-sg.zendesk.com/hc/en-us/articles/115015447167-I-want-to-cancel-my-food-order",
						"name":             "I want to cancel my food order",
						"title":            "I want to cancel my food order",
						"body":             "<p><strong>Can I cancel my food order? </strong></p>\\n<p>You may cancel your order before the restaurant has started preparing it. Simply go to <a href=\"https://www.honestbee.sg/en/food/orders\">Your Orders</a> and select the order you wish to cancel.</p>\\n<p>If you do not want your order to be delivered but the food is being prepared or our deliverer is on his way to you, please contact us for assistance. Do note that charges of the food order may still apply to you.</p>\\n<p> </p>\\n<p><button><a href=\"javascript:zE.show();zE.activate();\">Chat with Us</a></button></p>",
						"locale":           "en-us",
					},
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115015433907,
						"author_id":        24400224208,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         2,
						"vote_sum":         -12,
						"vote_count":       16,
						"created_at":       time.Date(2017, 11, 28, 13, 2, 47, 0, time.UTC),
						"updated_at":       time.Date(2018, 07, 17, 11, 3, 40, 0, time.UTC),
						"source_locale":    "en-us",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2018, 07, 10, 04, 26, 17, 0, time.UTC),
						"label_names":      []string{"ontheway", "delivered"},
						"country_code":     "sg",
						"url":              "https://honestbeehelp-sg.zendesk.com/api/v2/help_center/en-us/articles/115015433907-What-if-I-am-not-at-home-to-receive-my-order-.json",
						"html_url":         "https://honestbeehelp-sg.zendesk.com/hc/en-us/articles/115015433907-What-if-I-am-not-at-home-to-receive-my-order-",
						"name":             "What if I am not at home to receive my order?",
						"title":            "What if I am not at home to receive my order?",
						"body":             "<p>If you missed your delivery, please contact us as soon as possible. We will do our best to reschedule your delivery. We reserve the right to charge an additional redelivery fee of $15. Perishables such as meat and frozen food may be discarded in accordance with Food Safety Standards, and are not refundable on your order. </p>\\n<p> </p>\\n<p><button><a href=\"javascript:zE.show();zE.activate();\">Chat with Us</a></button></p>",
						"locale":           "en-us",
					},
				},
				"page":       1,
				"per_page":   30,
				"page_count": 1,
				"count":      4,
			},
		},
		{
			description: "testing normal en-us locale case with label_names confirmed,preparing,ontheway,delivered",
			addr:        "/api/categories/115002432448/articles",
			args: url.Values{
				"locale":       {"en-us"},
				"country_code": {"sg"},
				"label_names":  {"confirmed,preparing,ontheway,delivered"},
			},
			expectStatus: http.StatusOK,
			expect: map[string]interface{}{
				"articles": []interface{}{
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115016053147,
						"author_id":        7222048487,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         0,
						"vote_sum":         17,
						"vote_count":       33,
						"created_at":       time.Date(2018, 01, 12, 3, 24, 59, 0, time.UTC),
						"updated_at":       time.Date(2018, 07, 16, 13, 35, 30, 0, time.UTC),
						"source_locale":    "en-us",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2018, 07, 10, 4, 17, 18, 0, time.UTC),
						"label_names":      []string{"use_for_answer_bot", "preparing", "ontheway", "confirmed"},
						"country_code":     "sg",
						"url":              "https://honestbeehelp-sg.zendesk.com/api/v2/help_center/en-us/articles/115016053147-How-do-I-prepare-my-laundry-for-pickup-.json",
						"html_url":         "https://honestbeehelp-sg.zendesk.com/hc/en-us/articles/115016053147-How-do-I-prepare-my-laundry-for-pickup-",
						"name":             "How do I prepare my laundry for pickup?",
						"title":            "How do I prepare my laundry for pickup?",
						"body":             "<p>Please be ready with your laundry when the delivery bee comes. Also check that all clothing pockets are empty, as it will be difficult for us to trace personal articles after your laundry has been handed over. We will not be liable for missing personal articles after you hand it over to us as well.</p>",
						"locale":           "en-us",
					},
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115016039687,
						"author_id":        7222048487,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         0,
						"vote_sum":         -1,
						"vote_count":       9,
						"created_at":       time.Date(2018, 01, 11, 11, 49, 48, 0, time.UTC),
						"updated_at":       time.Date(2018, 07, 10, 04, 17, 49, 0, time.UTC),
						"source_locale":    "en-us",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2018, 01, 11, 11, 49, 48, 0, time.UTC),
						"label_names":      []string{"delivered"},
						"country_code":     "sg",
						"url":              "https://honestbeehelp-sg.zendesk.com/api/v2/help_center/en-us/articles/115016039687-I-have-not-received-my-order-confirmation-final-receipt.json",
						"html_url":         "https://honestbeehelp-sg.zendesk.com/hc/en-us/articles/115016039687-I-have-not-received-my-order-confirmation-final-receipt",
						"name":             "I have not received my order confirmation/final receipt",
						"title":            "I have not received my order confirmation/final receipt",
						"body":             "<p>We send you your order confirmation immediately after you have placed an order. There is a chance that it might have ended up in the junk/spam folder. Please let us know if you do not find it there.</p>\\n<p><br>We aim to send you your final receipt within 5 working days after we have returned your laundry. Please note that we might adjust your final receipt for any additional articles added to the order and the difference in weight (if any) of your wash and fold loads.</p>\\n<p><br>If this answer did not solve your issue, please contact us and we will do our best to make things right for you. </p>",
						"locale":           "en-us",
					},
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115015447167,
						"author_id":        24400224208,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         0,
						"vote_sum":         0,
						"vote_count":       -30,
						"created_at":       time.Date(2017, 11, 29, 2, 37, 50, 0, time.UTC),
						"updated_at":       time.Date(2018, 07, 14, 10, 33, 44, 0, time.UTC),
						"source_locale":    "en-us",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2018, 07, 9, 9, 49, 23, 0, time.UTC),
						"label_names":      []string{"preparing", "confirmed"},
						"country_code":     "sg",
						"url":              "https://honestbeehelp-sg.zendesk.com/api/v2/help_center/en-us/articles/115015447167-I-want-to-cancel-my-food-order.json",
						"html_url":         "https://honestbeehelp-sg.zendesk.com/hc/en-us/articles/115015447167-I-want-to-cancel-my-food-order",
						"name":             "I want to cancel my food order",
						"title":            "I want to cancel my food order",
						"body":             "<p><strong>Can I cancel my food order? </strong></p>\\n<p>You may cancel your order before the restaurant has started preparing it. Simply go to <a href=\"https://www.honestbee.sg/en/food/orders\">Your Orders</a> and select the order you wish to cancel.</p>\\n<p>If you do not want your order to be delivered but the food is being prepared or our deliverer is on his way to you, please contact us for assistance. Do note that charges of the food order may still apply to you.</p>\\n<p> </p>\\n<p><button><a href=\"javascript:zE.show();zE.activate();\">Chat with Us</a></button></p>",
						"locale":           "en-us",
					},
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115015433907,
						"author_id":        24400224208,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         2,
						"vote_sum":         -12,
						"vote_count":       16,
						"created_at":       time.Date(2017, 11, 28, 13, 2, 47, 0, time.UTC),
						"updated_at":       time.Date(2018, 07, 17, 11, 3, 40, 0, time.UTC),
						"source_locale":    "en-us",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2018, 07, 10, 04, 26, 17, 0, time.UTC),
						"label_names":      []string{"ontheway", "delivered"},
						"country_code":     "sg",
						"url":              "https://honestbeehelp-sg.zendesk.com/api/v2/help_center/en-us/articles/115015433907-What-if-I-am-not-at-home-to-receive-my-order-.json",
						"html_url":         "https://honestbeehelp-sg.zendesk.com/hc/en-us/articles/115015433907-What-if-I-am-not-at-home-to-receive-my-order-",
						"name":             "What if I am not at home to receive my order?",
						"title":            "What if I am not at home to receive my order?",
						"body":             "<p>If you missed your delivery, please contact us as soon as possible. We will do our best to reschedule your delivery. We reserve the right to charge an additional redelivery fee of $15. Perishables such as meat and frozen food may be discarded in accordance with Food Safety Standards, and are not refundable on your order. </p>\\n<p> </p>\\n<p><button><a href=\"javascript:zE.show();zE.activate();\">Chat with Us</a></button></p>",
						"locale":           "en-us",
					},
				},
				"page":       1,
				"per_page":   30,
				"page_count": 1,
				"count":      4,
			},
		},
		{
			description: "testing normal en-us locale case with label_names confirmed",
			addr:        "/api/categories/115002432448/articles",
			args: url.Values{
				"locale":       {"en-us"},
				"country_code": {"sg"},
				"label_names":  {"confirmed"},
			},
			expectStatus: http.StatusOK,
			expect: map[string]interface{}{
				"articles": []interface{}{
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115016053147,
						"author_id":        7222048487,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         0,
						"vote_sum":         17,
						"vote_count":       33,
						"created_at":       time.Date(2018, 01, 12, 3, 24, 59, 0, time.UTC),
						"updated_at":       time.Date(2018, 07, 16, 13, 35, 30, 0, time.UTC),
						"source_locale":    "en-us",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2018, 07, 10, 4, 17, 18, 0, time.UTC),
						"label_names":      []string{"use_for_answer_bot", "preparing", "ontheway", "confirmed"},
						"country_code":     "sg",
						"url":              "https://honestbeehelp-sg.zendesk.com/api/v2/help_center/en-us/articles/115016053147-How-do-I-prepare-my-laundry-for-pickup-.json",
						"html_url":         "https://honestbeehelp-sg.zendesk.com/hc/en-us/articles/115016053147-How-do-I-prepare-my-laundry-for-pickup-",
						"name":             "How do I prepare my laundry for pickup?",
						"title":            "How do I prepare my laundry for pickup?",
						"body":             "<p>Please be ready with your laundry when the delivery bee comes. Also check that all clothing pockets are empty, as it will be difficult for us to trace personal articles after your laundry has been handed over. We will not be liable for missing personal articles after you hand it over to us as well.</p>",
						"locale":           "en-us",
					},
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115015447167,
						"author_id":        24400224208,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         0,
						"vote_sum":         0,
						"vote_count":       -30,
						"created_at":       time.Date(2017, 11, 29, 2, 37, 50, 0, time.UTC),
						"updated_at":       time.Date(2018, 07, 14, 10, 33, 44, 0, time.UTC),
						"source_locale":    "en-us",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2018, 07, 9, 9, 49, 23, 0, time.UTC),
						"label_names":      []string{"preparing", "confirmed"},
						"country_code":     "sg",
						"url":              "https://honestbeehelp-sg.zendesk.com/api/v2/help_center/en-us/articles/115015447167-I-want-to-cancel-my-food-order.json",
						"html_url":         "https://honestbeehelp-sg.zendesk.com/hc/en-us/articles/115015447167-I-want-to-cancel-my-food-order",
						"name":             "I want to cancel my food order",
						"title":            "I want to cancel my food order",
						"body":             "<p><strong>Can I cancel my food order? </strong></p>\\n<p>You may cancel your order before the restaurant has started preparing it. Simply go to <a href=\"https://www.honestbee.sg/en/food/orders\">Your Orders</a> and select the order you wish to cancel.</p>\\n<p>If you do not want your order to be delivered but the food is being prepared or our deliverer is on his way to you, please contact us for assistance. Do note that charges of the food order may still apply to you.</p>\\n<p> </p>\\n<p><button><a href=\"javascript:zE.show();zE.activate();\">Chat with Us</a></button></p>",
						"locale":           "en-us",
					},
				},
				"page":       1,
				"per_page":   30,
				"page_count": 1,
				"count":      2,
			},
		},
		{
			description: "testing normal en-us locale case with label_names preparing",
			addr:        "/api/categories/115002432448/articles",
			args: url.Values{
				"locale":       {"en-us"},
				"country_code": {"sg"},
				"label_names":  {"preparing"},
			},
			expectStatus: http.StatusOK,
			expect: map[string]interface{}{
				"articles": []interface{}{
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115016053147,
						"author_id":        7222048487,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         0,
						"vote_sum":         17,
						"vote_count":       33,
						"created_at":       time.Date(2018, 01, 12, 3, 24, 59, 0, time.UTC),
						"updated_at":       time.Date(2018, 07, 16, 13, 35, 30, 0, time.UTC),
						"source_locale":    "en-us",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2018, 07, 10, 4, 17, 18, 0, time.UTC),
						"label_names":      []string{"use_for_answer_bot", "preparing", "ontheway", "confirmed"},
						"country_code":     "sg",
						"url":              "https://honestbeehelp-sg.zendesk.com/api/v2/help_center/en-us/articles/115016053147-How-do-I-prepare-my-laundry-for-pickup-.json",
						"html_url":         "https://honestbeehelp-sg.zendesk.com/hc/en-us/articles/115016053147-How-do-I-prepare-my-laundry-for-pickup-",
						"name":             "How do I prepare my laundry for pickup?",
						"title":            "How do I prepare my laundry for pickup?",
						"body":             "<p>Please be ready with your laundry when the delivery bee comes. Also check that all clothing pockets are empty, as it will be difficult for us to trace personal articles after your laundry has been handed over. We will not be liable for missing personal articles after you hand it over to us as well.</p>",
						"locale":           "en-us",
					},
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115015447167,
						"author_id":        24400224208,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         0,
						"vote_sum":         0,
						"vote_count":       -30,
						"created_at":       time.Date(2017, 11, 29, 2, 37, 50, 0, time.UTC),
						"updated_at":       time.Date(2018, 07, 14, 10, 33, 44, 0, time.UTC),
						"source_locale":    "en-us",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2018, 07, 9, 9, 49, 23, 0, time.UTC),
						"label_names":      []string{"preparing", "confirmed"},
						"country_code":     "sg",
						"url":              "https://honestbeehelp-sg.zendesk.com/api/v2/help_center/en-us/articles/115015447167-I-want-to-cancel-my-food-order.json",
						"html_url":         "https://honestbeehelp-sg.zendesk.com/hc/en-us/articles/115015447167-I-want-to-cancel-my-food-order",
						"name":             "I want to cancel my food order",
						"title":            "I want to cancel my food order",
						"body":             "<p><strong>Can I cancel my food order? </strong></p>\\n<p>You may cancel your order before the restaurant has started preparing it. Simply go to <a href=\"https://www.honestbee.sg/en/food/orders\">Your Orders</a> and select the order you wish to cancel.</p>\\n<p>If you do not want your order to be delivered but the food is being prepared or our deliverer is on his way to you, please contact us for assistance. Do note that charges of the food order may still apply to you.</p>\\n<p> </p>\\n<p><button><a href=\"javascript:zE.show();zE.activate();\">Chat with Us</a></button></p>",
						"locale":           "en-us",
					},
				},
				"page":       1,
				"per_page":   30,
				"page_count": 1,
				"count":      2,
			},
		},
		{
			description: "testing normal en-us locale case with label_names ontheway",
			addr:        "/api/categories/115002432448/articles",
			args: url.Values{
				"locale":       {"en-us"},
				"country_code": {"sg"},
				"label_names":  {"ontheway"},
			},
			expectStatus: http.StatusOK,
			expect: map[string]interface{}{
				"articles": []interface{}{
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115016053147,
						"author_id":        7222048487,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         0,
						"vote_sum":         17,
						"vote_count":       33,
						"created_at":       time.Date(2018, 01, 12, 3, 24, 59, 0, time.UTC),
						"updated_at":       time.Date(2018, 07, 16, 13, 35, 30, 0, time.UTC),
						"source_locale":    "en-us",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2018, 07, 10, 4, 17, 18, 0, time.UTC),
						"label_names":      []string{"use_for_answer_bot", "preparing", "ontheway", "confirmed"},
						"country_code":     "sg",
						"url":              "https://honestbeehelp-sg.zendesk.com/api/v2/help_center/en-us/articles/115016053147-How-do-I-prepare-my-laundry-for-pickup-.json",
						"html_url":         "https://honestbeehelp-sg.zendesk.com/hc/en-us/articles/115016053147-How-do-I-prepare-my-laundry-for-pickup-",
						"name":             "How do I prepare my laundry for pickup?",
						"title":            "How do I prepare my laundry for pickup?",
						"body":             "<p>Please be ready with your laundry when the delivery bee comes. Also check that all clothing pockets are empty, as it will be difficult for us to trace personal articles after your laundry has been handed over. We will not be liable for missing personal articles after you hand it over to us as well.</p>",
						"locale":           "en-us",
					},
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115015433907,
						"author_id":        24400224208,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         2,
						"vote_sum":         -12,
						"vote_count":       16,
						"created_at":       time.Date(2017, 11, 28, 13, 2, 47, 0, time.UTC),
						"updated_at":       time.Date(2018, 07, 17, 11, 3, 40, 0, time.UTC),
						"source_locale":    "en-us",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2018, 07, 10, 04, 26, 17, 0, time.UTC),
						"label_names":      []string{"ontheway", "delivered"},
						"country_code":     "sg",
						"url":              "https://honestbeehelp-sg.zendesk.com/api/v2/help_center/en-us/articles/115015433907-What-if-I-am-not-at-home-to-receive-my-order-.json",
						"html_url":         "https://honestbeehelp-sg.zendesk.com/hc/en-us/articles/115015433907-What-if-I-am-not-at-home-to-receive-my-order-",
						"name":             "What if I am not at home to receive my order?",
						"title":            "What if I am not at home to receive my order?",
						"body":             "<p>If you missed your delivery, please contact us as soon as possible. We will do our best to reschedule your delivery. We reserve the right to charge an additional redelivery fee of $15. Perishables such as meat and frozen food may be discarded in accordance with Food Safety Standards, and are not refundable on your order. </p>\\n<p> </p>\\n<p><button><a href=\"javascript:zE.show();zE.activate();\">Chat with Us</a></button></p>",
						"locale":           "en-us",
					},
				},
				"page":       1,
				"per_page":   30,
				"page_count": 1,
				"count":      2,
			},
		},
		{
			description: "testing normal en-us locale case with label_names delivered",
			addr:        "/api/categories/115002432448/articles",
			args: url.Values{
				"locale":       {"en-us"},
				"country_code": {"sg"},
				"label_names":  {"delivered"},
			},
			expectStatus: http.StatusOK,
			expect: map[string]interface{}{
				"articles": []interface{}{
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115016039687,
						"author_id":        7222048487,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         0,
						"vote_sum":         -1,
						"vote_count":       9,
						"created_at":       time.Date(2018, 01, 11, 11, 49, 48, 0, time.UTC),
						"updated_at":       time.Date(2018, 07, 10, 04, 17, 49, 0, time.UTC),
						"source_locale":    "en-us",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2018, 01, 11, 11, 49, 48, 0, time.UTC),
						"label_names":      []string{"delivered"},
						"country_code":     "sg",
						"url":              "https://honestbeehelp-sg.zendesk.com/api/v2/help_center/en-us/articles/115016039687-I-have-not-received-my-order-confirmation-final-receipt.json",
						"html_url":         "https://honestbeehelp-sg.zendesk.com/hc/en-us/articles/115016039687-I-have-not-received-my-order-confirmation-final-receipt",
						"name":             "I have not received my order confirmation/final receipt",
						"title":            "I have not received my order confirmation/final receipt",
						"body":             "<p>We send you your order confirmation immediately after you have placed an order. There is a chance that it might have ended up in the junk/spam folder. Please let us know if you do not find it there.</p>\\n<p><br>We aim to send you your final receipt within 5 working days after we have returned your laundry. Please note that we might adjust your final receipt for any additional articles added to the order and the difference in weight (if any) of your wash and fold loads.</p>\\n<p><br>If this answer did not solve your issue, please contact us and we will do our best to make things right for you. </p>",
						"locale":           "en-us",
					},
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115015433907,
						"author_id":        24400224208,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         2,
						"vote_sum":         -12,
						"vote_count":       16,
						"created_at":       time.Date(2017, 11, 28, 13, 2, 47, 0, time.UTC),
						"updated_at":       time.Date(2018, 07, 17, 11, 3, 40, 0, time.UTC),
						"source_locale":    "en-us",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2018, 07, 10, 04, 26, 17, 0, time.UTC),
						"label_names":      []string{"ontheway", "delivered"},
						"country_code":     "sg",
						"url":              "https://honestbeehelp-sg.zendesk.com/api/v2/help_center/en-us/articles/115015433907-What-if-I-am-not-at-home-to-receive-my-order-.json",
						"html_url":         "https://honestbeehelp-sg.zendesk.com/hc/en-us/articles/115015433907-What-if-I-am-not-at-home-to-receive-my-order-",
						"name":             "What if I am not at home to receive my order?",
						"title":            "What if I am not at home to receive my order?",
						"body":             "<p>If you missed your delivery, please contact us as soon as possible. We will do our best to reschedule your delivery. We reserve the right to charge an additional redelivery fee of $15. Perishables such as meat and frozen food may be discarded in accordance with Food Safety Standards, and are not refundable on your order. </p>\\n<p> </p>\\n<p><button><a href=\"javascript:zE.show();zE.activate();\">Chat with Us</a></button></p>",
						"locale":           "en-us",
					},
				},
				"page":       1,
				"per_page":   30,
				"page_count": 1,
				"count":      2,
			},
		},
		{
			description: "testing not exist locale case",
			addr:        "/api/categories/115002432448/articles",
			args: url.Values{
				"locale":       {"not-exist-locale"},
				"country_code": {"sg"},
				"label_names":  {"confirmed,preparing,ontheway,delivered"},
			},
			expectStatus: http.StatusBadRequest,
			expect: map[string]interface{}{
				"error": errs.InvalidAttributeErrorMsg,
			},
		},
		{
			description: "testing not exist country code case",
			addr:        "/api/categories/115002432448/articles",
			args: url.Values{
				"locale":       {"en-us"},
				"country_code": {"not-exist-country-code"},
				"label_names":  {"confirmed,preparing,ontheway,delivered"},
			},
			expectStatus: http.StatusBadRequest,
			expect: map[string]interface{}{
				"error": errs.InvalidAttributeErrorMsg,
			},
		},
		{
			description: "testing not exist country code and locale case",
			addr:        "/api/categories/115002432448/articles",
			args: url.Values{
				"locale":       {"not-exist-locale"},
				"country_code": {"not-exist-country-code"},
				"label_names":  {"confirmed,preparing,ontheway,delivered"},
			},
			expectStatus: http.StatusBadRequest,
			expect: map[string]interface{}{
				"error": errs.InvalidAttributeErrorMsg,
			},
		},
		{
			description: "testing not 0 per page case",
			addr:        "/api/categories/115002432448/articles",
			args: url.Values{
				"locale":       {"en-us"},
				"country_code": {"sg"},
				"per_page":     {"0"},
				"label_names":  {"confirmed,preparing,ontheway,delivered"},
			},
			expectStatus: http.StatusBadRequest,
			expect: map[string]interface{}{
				"error": errs.InvalidAttributeErrorMsg,
			},
		},
		{
			description: "testing not 0 page case",
			addr:        "/api/categories/115002432448/sections",
			args: url.Values{
				"locale":       {"en-us"},
				"country_code": {"tw"},
				"page":         {"0"},
				"label_names":  {"confirmed,preparing,ontheway,delivered"},
			},
			expectStatus: http.StatusBadRequest,
			expect: map[string]interface{}{
				"error": errs.InvalidAttributeErrorMsg,
			},
		},
		{
			description: "testing not 0 page and 0 per page case",
			addr:        "/api/categories/115002432448/articles",
			args: url.Values{
				"locale":       {"en-us"},
				"country_code": {"sg"},
				"page":         {"0"},
				"per_page":     {"0"},
				"label_names":  {"confirmed,preparing,ontheway,delivered"},
			},
			expectStatus: http.StatusBadRequest,
			expect: map[string]interface{}{
				"error": errs.InvalidAttributeErrorMsg,
			},
		},
		{
			description: "testing sort by created at case",
			addr:        "/api/categories/115002432448/articles",
			args: url.Values{
				"locale":       {"en-us"},
				"country_code": {"sg"},
				"sort_by":      {"created_at"},
				"label_names":  {"confirmed,preparing,ontheway,delivered"},
			},
			expectStatus: http.StatusOK,
			expect: map[string]interface{}{
				"articles": []interface{}{
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115015433907,
						"author_id":        24400224208,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         2,
						"vote_sum":         -12,
						"vote_count":       16,
						"created_at":       time.Date(2017, 11, 28, 13, 2, 47, 0, time.UTC),
						"updated_at":       time.Date(2018, 07, 17, 11, 3, 40, 0, time.UTC),
						"source_locale":    "en-us",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2018, 07, 10, 04, 26, 17, 0, time.UTC),
						"label_names":      []string{"ontheway", "delivered"},
						"country_code":     "sg",
						"url":              "https://honestbeehelp-sg.zendesk.com/api/v2/help_center/en-us/articles/115015433907-What-if-I-am-not-at-home-to-receive-my-order-.json",
						"html_url":         "https://honestbeehelp-sg.zendesk.com/hc/en-us/articles/115015433907-What-if-I-am-not-at-home-to-receive-my-order-",
						"name":             "What if I am not at home to receive my order?",
						"title":            "What if I am not at home to receive my order?",
						"body":             "<p>If you missed your delivery, please contact us as soon as possible. We will do our best to reschedule your delivery. We reserve the right to charge an additional redelivery fee of $15. Perishables such as meat and frozen food may be discarded in accordance with Food Safety Standards, and are not refundable on your order. </p>\\n<p> </p>\\n<p><button><a href=\"javascript:zE.show();zE.activate();\">Chat with Us</a></button></p>",
						"locale":           "en-us",
					},
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115015447167,
						"author_id":        24400224208,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         0,
						"vote_sum":         0,
						"vote_count":       -30,
						"created_at":       time.Date(2017, 11, 29, 2, 37, 50, 0, time.UTC),
						"updated_at":       time.Date(2018, 07, 14, 10, 33, 44, 0, time.UTC),
						"source_locale":    "en-us",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2018, 07, 9, 9, 49, 23, 0, time.UTC),
						"label_names":      []string{"preparing", "confirmed"},
						"country_code":     "sg",
						"url":              "https://honestbeehelp-sg.zendesk.com/api/v2/help_center/en-us/articles/115015447167-I-want-to-cancel-my-food-order.json",
						"html_url":         "https://honestbeehelp-sg.zendesk.com/hc/en-us/articles/115015447167-I-want-to-cancel-my-food-order",
						"name":             "I want to cancel my food order",
						"title":            "I want to cancel my food order",
						"body":             "<p><strong>Can I cancel my food order? </strong></p>\\n<p>You may cancel your order before the restaurant has started preparing it. Simply go to <a href=\"https://www.honestbee.sg/en/food/orders\">Your Orders</a> and select the order you wish to cancel.</p>\\n<p>If you do not want your order to be delivered but the food is being prepared or our deliverer is on his way to you, please contact us for assistance. Do note that charges of the food order may still apply to you.</p>\\n<p> </p>\\n<p><button><a href=\"javascript:zE.show();zE.activate();\">Chat with Us</a></button></p>",
						"locale":           "en-us",
					},
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115016039687,
						"author_id":        7222048487,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         0,
						"vote_sum":         -1,
						"vote_count":       9,
						"created_at":       time.Date(2018, 01, 11, 11, 49, 48, 0, time.UTC),
						"updated_at":       time.Date(2018, 07, 10, 04, 17, 49, 0, time.UTC),
						"source_locale":    "en-us",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2018, 01, 11, 11, 49, 48, 0, time.UTC),
						"label_names":      []string{"delivered"},
						"country_code":     "sg",
						"url":              "https://honestbeehelp-sg.zendesk.com/api/v2/help_center/en-us/articles/115016039687-I-have-not-received-my-order-confirmation-final-receipt.json",
						"html_url":         "https://honestbeehelp-sg.zendesk.com/hc/en-us/articles/115016039687-I-have-not-received-my-order-confirmation-final-receipt",
						"name":             "I have not received my order confirmation/final receipt",
						"title":            "I have not received my order confirmation/final receipt",
						"body":             "<p>We send you your order confirmation immediately after you have placed an order. There is a chance that it might have ended up in the junk/spam folder. Please let us know if you do not find it there.</p>\\n<p><br>We aim to send you your final receipt within 5 working days after we have returned your laundry. Please note that we might adjust your final receipt for any additional articles added to the order and the difference in weight (if any) of your wash and fold loads.</p>\\n<p><br>If this answer did not solve your issue, please contact us and we will do our best to make things right for you. </p>",
						"locale":           "en-us",
					},
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115016053147,
						"author_id":        7222048487,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         0,
						"vote_sum":         17,
						"vote_count":       33,
						"created_at":       time.Date(2018, 01, 12, 3, 24, 59, 0, time.UTC),
						"updated_at":       time.Date(2018, 07, 16, 13, 35, 30, 0, time.UTC),
						"source_locale":    "en-us",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2018, 07, 10, 4, 17, 18, 0, time.UTC),
						"label_names":      []string{"use_for_answer_bot", "preparing", "ontheway", "confirmed"},
						"country_code":     "sg",
						"url":              "https://honestbeehelp-sg.zendesk.com/api/v2/help_center/en-us/articles/115016053147-How-do-I-prepare-my-laundry-for-pickup-.json",
						"html_url":         "https://honestbeehelp-sg.zendesk.com/hc/en-us/articles/115016053147-How-do-I-prepare-my-laundry-for-pickup-",
						"name":             "How do I prepare my laundry for pickup?",
						"title":            "How do I prepare my laundry for pickup?",
						"body":             "<p>Please be ready with your laundry when the delivery bee comes. Also check that all clothing pockets are empty, as it will be difficult for us to trace personal articles after your laundry has been handed over. We will not be liable for missing personal articles after you hand it over to us as well.</p>",
						"locale":           "en-us",
					},
				},
				"page":       1,
				"per_page":   30,
				"page_count": 1,
				"count":      4,
			},
		},
		{
			description: "testing sort by updated at case",
			addr:        "/api/categories/115002432448/articles",
			args: url.Values{
				"locale":       {"en-us"},
				"country_code": {"sg"},
				"sort_by":      {"updated_at"},
				"label_names":  {"confirmed,preparing,ontheway,delivered"},
			},
			expectStatus: http.StatusOK,
			expect: map[string]interface{}{
				"articles": []interface{}{
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115016039687,
						"author_id":        7222048487,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         0,
						"vote_sum":         -1,
						"vote_count":       9,
						"created_at":       time.Date(2018, 01, 11, 11, 49, 48, 0, time.UTC),
						"updated_at":       time.Date(2018, 07, 10, 04, 17, 49, 0, time.UTC),
						"source_locale":    "en-us",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2018, 01, 11, 11, 49, 48, 0, time.UTC),
						"label_names":      []string{"delivered"},
						"country_code":     "sg",
						"url":              "https://honestbeehelp-sg.zendesk.com/api/v2/help_center/en-us/articles/115016039687-I-have-not-received-my-order-confirmation-final-receipt.json",
						"html_url":         "https://honestbeehelp-sg.zendesk.com/hc/en-us/articles/115016039687-I-have-not-received-my-order-confirmation-final-receipt",
						"name":             "I have not received my order confirmation/final receipt",
						"title":            "I have not received my order confirmation/final receipt",
						"body":             "<p>We send you your order confirmation immediately after you have placed an order. There is a chance that it might have ended up in the junk/spam folder. Please let us know if you do not find it there.</p>\\n<p><br>We aim to send you your final receipt within 5 working days after we have returned your laundry. Please note that we might adjust your final receipt for any additional articles added to the order and the difference in weight (if any) of your wash and fold loads.</p>\\n<p><br>If this answer did not solve your issue, please contact us and we will do our best to make things right for you. </p>",
						"locale":           "en-us",
					},
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115015447167,
						"author_id":        24400224208,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         0,
						"vote_sum":         0,
						"vote_count":       -30,
						"created_at":       time.Date(2017, 11, 29, 2, 37, 50, 0, time.UTC),
						"updated_at":       time.Date(2018, 07, 14, 10, 33, 44, 0, time.UTC),
						"source_locale":    "en-us",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2018, 07, 9, 9, 49, 23, 0, time.UTC),
						"label_names":      []string{"preparing", "confirmed"},
						"country_code":     "sg",
						"url":              "https://honestbeehelp-sg.zendesk.com/api/v2/help_center/en-us/articles/115015447167-I-want-to-cancel-my-food-order.json",
						"html_url":         "https://honestbeehelp-sg.zendesk.com/hc/en-us/articles/115015447167-I-want-to-cancel-my-food-order",
						"name":             "I want to cancel my food order",
						"title":            "I want to cancel my food order",
						"body":             "<p><strong>Can I cancel my food order? </strong></p>\\n<p>You may cancel your order before the restaurant has started preparing it. Simply go to <a href=\"https://www.honestbee.sg/en/food/orders\">Your Orders</a> and select the order you wish to cancel.</p>\\n<p>If you do not want your order to be delivered but the food is being prepared or our deliverer is on his way to you, please contact us for assistance. Do note that charges of the food order may still apply to you.</p>\\n<p> </p>\\n<p><button><a href=\"javascript:zE.show();zE.activate();\">Chat with Us</a></button></p>",
						"locale":           "en-us",
					},
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115016053147,
						"author_id":        7222048487,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         0,
						"vote_sum":         17,
						"vote_count":       33,
						"created_at":       time.Date(2018, 01, 12, 3, 24, 59, 0, time.UTC),
						"updated_at":       time.Date(2018, 07, 16, 13, 35, 30, 0, time.UTC),
						"source_locale":    "en-us",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2018, 07, 10, 4, 17, 18, 0, time.UTC),
						"label_names":      []string{"use_for_answer_bot", "preparing", "ontheway", "confirmed"},
						"country_code":     "sg",
						"url":              "https://honestbeehelp-sg.zendesk.com/api/v2/help_center/en-us/articles/115016053147-How-do-I-prepare-my-laundry-for-pickup-.json",
						"html_url":         "https://honestbeehelp-sg.zendesk.com/hc/en-us/articles/115016053147-How-do-I-prepare-my-laundry-for-pickup-",
						"name":             "How do I prepare my laundry for pickup?",
						"title":            "How do I prepare my laundry for pickup?",
						"body":             "<p>Please be ready with your laundry when the delivery bee comes. Also check that all clothing pockets are empty, as it will be difficult for us to trace personal articles after your laundry has been handed over. We will not be liable for missing personal articles after you hand it over to us as well.</p>",
						"locale":           "en-us",
					},
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115015433907,
						"author_id":        24400224208,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         2,
						"vote_sum":         -12,
						"vote_count":       16,
						"created_at":       time.Date(2017, 11, 28, 13, 2, 47, 0, time.UTC),
						"updated_at":       time.Date(2018, 07, 17, 11, 3, 40, 0, time.UTC),
						"source_locale":    "en-us",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2018, 07, 10, 04, 26, 17, 0, time.UTC),
						"label_names":      []string{"ontheway", "delivered"},
						"country_code":     "sg",
						"url":              "https://honestbeehelp-sg.zendesk.com/api/v2/help_center/en-us/articles/115015433907-What-if-I-am-not-at-home-to-receive-my-order-.json",
						"html_url":         "https://honestbeehelp-sg.zendesk.com/hc/en-us/articles/115015433907-What-if-I-am-not-at-home-to-receive-my-order-",
						"name":             "What if I am not at home to receive my order?",
						"title":            "What if I am not at home to receive my order?",
						"body":             "<p>If you missed your delivery, please contact us as soon as possible. We will do our best to reschedule your delivery. We reserve the right to charge an additional redelivery fee of $15. Perishables such as meat and frozen food may be discarded in accordance with Food Safety Standards, and are not refundable on your order. </p>\\n<p> </p>\\n<p><button><a href=\"javascript:zE.show();zE.activate();\">Chat with Us</a></button></p>",
						"locale":           "en-us",
					},
				},
				"page":       1,
				"per_page":   30,
				"page_count": 1,
				"count":      4,
			},
		},
		{
			description: "testing sort by not correct case",
			addr:        "/api/categories/115002432448/articles",
			args: url.Values{
				"locale":       {"en-us"},
				"country_code": {"sg"},
				"sort_by":      {"unknown-sort-by"},
				"label_names":  {"confirmed,preparing,ontheway,delivered"},
			},
			expectStatus: http.StatusBadRequest,
			expect: map[string]interface{}{
				"error": errs.InvalidAttributeErrorMsg,
			},
		},
		{
			description: "testing sort order desc case",
			addr:        "/api/categories/115002432448/articles",
			args: url.Values{
				"locale":       {"en-us"},
				"country_code": {"sg"},
				"sort_order":   {"desc"},
				"label_names":  {"confirmed,preparing,ontheway,delivered"},
			},
			expectStatus: http.StatusOK,
			expect: map[string]interface{}{
				"articles": []interface{}{
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115015433907,
						"author_id":        24400224208,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         2,
						"vote_sum":         -12,
						"vote_count":       16,
						"created_at":       time.Date(2017, 11, 28, 13, 2, 47, 0, time.UTC),
						"updated_at":       time.Date(2018, 07, 17, 11, 3, 40, 0, time.UTC),
						"source_locale":    "en-us",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2018, 07, 10, 04, 26, 17, 0, time.UTC),
						"label_names":      []string{"ontheway", "delivered"},
						"country_code":     "sg",
						"url":              "https://honestbeehelp-sg.zendesk.com/api/v2/help_center/en-us/articles/115015433907-What-if-I-am-not-at-home-to-receive-my-order-.json",
						"html_url":         "https://honestbeehelp-sg.zendesk.com/hc/en-us/articles/115015433907-What-if-I-am-not-at-home-to-receive-my-order-",
						"name":             "What if I am not at home to receive my order?",
						"title":            "What if I am not at home to receive my order?",
						"body":             "<p>If you missed your delivery, please contact us as soon as possible. We will do our best to reschedule your delivery. We reserve the right to charge an additional redelivery fee of $15. Perishables such as meat and frozen food may be discarded in accordance with Food Safety Standards, and are not refundable on your order. </p>\\n<p> </p>\\n<p><button><a href=\"javascript:zE.show();zE.activate();\">Chat with Us</a></button></p>",
						"locale":           "en-us",
					},
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115016053147,
						"author_id":        7222048487,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         0,
						"vote_sum":         17,
						"vote_count":       33,
						"created_at":       time.Date(2018, 01, 12, 3, 24, 59, 0, time.UTC),
						"updated_at":       time.Date(2018, 07, 16, 13, 35, 30, 0, time.UTC),
						"source_locale":    "en-us",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2018, 07, 10, 4, 17, 18, 0, time.UTC),
						"label_names":      []string{"use_for_answer_bot", "preparing", "ontheway", "confirmed"},
						"country_code":     "sg",
						"url":              "https://honestbeehelp-sg.zendesk.com/api/v2/help_center/en-us/articles/115016053147-How-do-I-prepare-my-laundry-for-pickup-.json",
						"html_url":         "https://honestbeehelp-sg.zendesk.com/hc/en-us/articles/115016053147-How-do-I-prepare-my-laundry-for-pickup-",
						"name":             "How do I prepare my laundry for pickup?",
						"title":            "How do I prepare my laundry for pickup?",
						"body":             "<p>Please be ready with your laundry when the delivery bee comes. Also check that all clothing pockets are empty, as it will be difficult for us to trace personal articles after your laundry has been handed over. We will not be liable for missing personal articles after you hand it over to us as well.</p>",
						"locale":           "en-us",
					},
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115016039687,
						"author_id":        7222048487,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         0,
						"vote_sum":         -1,
						"vote_count":       9,
						"created_at":       time.Date(2018, 01, 11, 11, 49, 48, 0, time.UTC),
						"updated_at":       time.Date(2018, 07, 10, 04, 17, 49, 0, time.UTC),
						"source_locale":    "en-us",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2018, 01, 11, 11, 49, 48, 0, time.UTC),
						"label_names":      []string{"delivered"},
						"country_code":     "sg",
						"url":              "https://honestbeehelp-sg.zendesk.com/api/v2/help_center/en-us/articles/115016039687-I-have-not-received-my-order-confirmation-final-receipt.json",
						"html_url":         "https://honestbeehelp-sg.zendesk.com/hc/en-us/articles/115016039687-I-have-not-received-my-order-confirmation-final-receipt",
						"name":             "I have not received my order confirmation/final receipt",
						"title":            "I have not received my order confirmation/final receipt",
						"body":             "<p>We send you your order confirmation immediately after you have placed an order. There is a chance that it might have ended up in the junk/spam folder. Please let us know if you do not find it there.</p>\\n<p><br>We aim to send you your final receipt within 5 working days after we have returned your laundry. Please note that we might adjust your final receipt for any additional articles added to the order and the difference in weight (if any) of your wash and fold loads.</p>\\n<p><br>If this answer did not solve your issue, please contact us and we will do our best to make things right for you. </p>",
						"locale":           "en-us",
					},
					map[string]interface{}{
						"section_id":       115004118448,
						"id":               115015447167,
						"author_id":        24400224208,
						"comments_disable": false,
						"draft":            false,
						"promoted":         false,
						"position":         0,
						"vote_sum":         0,
						"vote_count":       -30,
						"created_at":       time.Date(2017, 11, 29, 2, 37, 50, 0, time.UTC),
						"updated_at":       time.Date(2018, 07, 14, 10, 33, 44, 0, time.UTC),
						"source_locale":    "en-us",
						"outdated":         false,
						"outdated_locales": []string{},
						"edited_at":        time.Date(2018, 07, 9, 9, 49, 23, 0, time.UTC),
						"label_names":      []string{"preparing", "confirmed"},
						"country_code":     "sg",
						"url":              "https://honestbeehelp-sg.zendesk.com/api/v2/help_center/en-us/articles/115015447167-I-want-to-cancel-my-food-order.json",
						"html_url":         "https://honestbeehelp-sg.zendesk.com/hc/en-us/articles/115015447167-I-want-to-cancel-my-food-order",
						"name":             "I want to cancel my food order",
						"title":            "I want to cancel my food order",
						"body":             "<p><strong>Can I cancel my food order? </strong></p>\\n<p>You may cancel your order before the restaurant has started preparing it. Simply go to <a href=\"https://www.honestbee.sg/en/food/orders\">Your Orders</a> and select the order you wish to cancel.</p>\\n<p>If you do not want your order to be delivered but the food is being prepared or our deliverer is on his way to you, please contact us for assistance. Do note that charges of the food order may still apply to you.</p>\\n<p> </p>\\n<p><button><a href=\"javascript:zE.show();zE.activate();\">Chat with Us</a></button></p>",
						"locale":           "en-us",
					},
				},
				"page":       1,
				"per_page":   30,
				"page_count": 1,
				"count":      4,
			},
		},
		{
			description: "testing sort order not correct case",
			addr:        "/api/categories/115002432448/articles",
			args: url.Values{
				"locale":       {"en-us"},
				"country_code": {"sg"},
				"sort_order":   {"unknown-sort-order"},
				"label_names":  {"confirmed,preparing,ontheway,delivered"},
			},
			expectStatus: http.StatusBadRequest,
			expect: map[string]interface{}{
				"error": errs.InvalidAttributeErrorMsg,
			},
		},
	}

	for _, tt := range testCases {
		t.Run(tt.description, func(t *testing.T) {
			resp, err := ts.Client().Get(ts.URL + tt.addr + "?" + tt.args.Encode())
			if err != nil {
				t.Fatalf("[%s] http client do failed:%v", tt.description, err)
			}
			defer resp.Body.Close()

			if tt.expectStatus != resp.StatusCode {
				t.Errorf("[%s] http status expect:%v != actual:%v", tt.description, tt.expectStatus, resp.Status)
			}

			actual := make(map[string]interface{})
			if err = json.NewDecoder(resp.Body).Decode(&actual); err != nil {
				t.Fatalf("[%s] json decoding failed:%v", tt.description, err)
			}
			expectData, err := json.Marshal(tt.expect)
			if err != nil {
				t.Fatalf("[%s] json marshal failed:%v", tt.description, err)
			}
			expect := make(map[string]interface{})
			if err = json.Unmarshal(expectData, &expect); err != nil {
				t.Fatalf("[%s] json unmarshal failed:%v", tt.description, err)
			}
			if diff := deep.Equal(expect, actual); diff != nil {
				t.Errorf("[%s] %v", tt.description, diff)
			}
		})
	}
}
